"""
npz_to_cube_batch.py
====================
批次將 qsar_grid_maps/ 目錄下所有 .npz 轉換為 .cube 檔案。

用法：
  python npz_to_cube_batch.py                        ← 互動式，詢問目錄
  python npz_to_cube_batch.py --input qsar_grid_maps
  python npz_to_cube_batch.py --input qsar_grid_maps --fields perturb_steric perturb_electro
  python npz_to_cube_batch.py --input qsar_grid_maps --workers 8
"""

import os, sys, gc, json, time, argparse, traceback
import multiprocessing
import threading
import numpy as np

# ── ANSI 顏色 ─────────────────────────────────────────────────────────────────
_C = {
    "reset": "\033[0m","bold":   "\033[1m",
    "cyan":  "\033[96m","green": "\033[92m",
    "yellow":"\033[93m","red":   "\033[91m",
    "dim":   "\033[2m",
}
def _c(text, *keys):
    if not sys.stdout.isatty(): return str(text)
    return "".join(_C.get(k,"") for k in keys) + str(text) + _C["reset"]

def _hr(char="─", width=62):
    return _c(char * width, "dim")

# ── 可選場名稱與說明 ──────────────────────────────────────────────────────────
ALL_FIELDS = [
    "saliency_total",
    "saliency_electro",
    "saliency_steric",
    "perturb_steric",
    "perturb_electro",
    "ig_total",
]

FIELD_LABELS = {
    "saliency_total":   "Saliency Total",
    "saliency_electro": "Saliency Electrostatic",
    "saliency_steric":  "Saliency Steric",
    "perturb_steric":   "Perturbation Steric  (DS: Green+2/Yellow-2)",
    "perturb_electro":  "Perturbation Electro (DS: Blue+2/Red-2)",
    "ig_total":         "Integrated Gradients",
}

ANGSTROM_TO_BOHR = 1.0 / 0.529177

# ══════════════════════════════════════════════════════════════════════════════
# 核心：單一 .npz → 多個 .cube
# ══════════════════════════════════════════════════════════════════════════════

def _write_cube_from_arrays(path, atomic_nums, atomic_coords,
                             grid_data, origin, axes, title="QSAR"):
    """寫出 Gaussian cube 格式（純函式，不依賴 qsar_grid_map.py）。"""
    A2B      = ANGSTROM_TO_BOHR
    nx,ny,nz = grid_data.shape
    n_atoms  = len(atomic_nums)
    ox,oy,oz = origin * A2B
    with open(path, "w") as f:
        f.write(f"QSAR CONTRIBUTION FIELD: {title}\n")
        f.write("Generated by npz_to_cube_batch.py\n")
        f.write(f"{n_atoms:5d} {ox:12.6f} {oy:12.6f} {oz:12.6f}\n")
        for i in range(3):
            f.write(f"{[nx,ny,nz][i]:5d} "
                    f"{axes[i,0]*A2B:12.6f} "
                    f"{axes[i,1]*A2B:12.6f} "
                    f"{axes[i,2]*A2B:12.6f}\n")
        for anum, (x,y,z) in zip(atomic_nums, atomic_coords):
            f.write(f"{int(anum):5d} {0.0:12.6f} "
                    f"{x*A2B:12.6f} {y*A2B:12.6f} {z*A2B:12.6f}\n")
        flat = grid_data.ravel()
        for i in range(0, len(flat), 6):
            f.write(" ".join(f"{v:13.5E}" for v in flat[i:i+6]) + "\n")


def convert_npz(npz_path: str, output_dir: str,
                fields: list | None = None) -> tuple:
    """
    將單一 .npz 轉換為指定場的 .cube 檔案。

    回傳 (mol_name, n_written, [error_str | None])
    Windows 安全：使用 mmap_mode=None + 明確 close()。
    """
    mol_name  = os.path.splitext(os.path.basename(npz_path))[0]
    written   = []

    try:
        # ── 讀取 npz（mmap_mode=None 避免 Windows handle 殘留）──────────────
        npzfile = np.load(npz_path, allow_pickle=True, mmap_mode=None)
        try:
            meta          = json.loads(str(npzfile["_meta"][0]))
            origin        = np.array(meta["origin"],  dtype=np.float64)
            axes          = np.array(meta["axes"],    dtype=np.float64)
            atomic_nums   = npzfile["atomic_nums"].astype(np.int32)
            atomic_coords = npzfile["atomic_coords"].astype(np.float64)

            field_map = {
                "saliency_total":   f"Saliency Total:{mol_name}",
                "saliency_electro": f"Saliency Electrostatic:{mol_name}",
                "saliency_steric":  f"Saliency Steric:{mol_name}",
                "perturb_steric":   f"Perturbation Steric:{mol_name}",
                "perturb_electro":  f"Perturbation Electro:{mol_name}",
                "ig_total":         f"IG:{mol_name}",
            }

            to_export = fields if fields else ALL_FIELDS
            # 把需要的場資料全部讀進記憶體
            field_data = {}
            for key in to_export:
                if key in npzfile:
                    field_data[key] = npzfile[key].astype(np.float64)
        finally:
            npzfile.close()   # 明確釋放 handle（Windows 必須）
            del npzfile
            gc.collect()

        # ── 寫出 .cube ────────────────────────────────────────────────────────
        os.makedirs(output_dir, exist_ok=True)
        for key, arr in field_data.items():
            cube_path = os.path.join(output_dir, f"{mol_name}_{key}.cube")
            _write_cube_from_arrays(
                cube_path, atomic_nums, atomic_coords,
                arr, origin, axes, title=field_map.get(key, key))
            written.append(cube_path)

        return mol_name, len(written), None

    except Exception:
        return mol_name, 0, traceback.format_exc(limit=4)


# ══════════════════════════════════════════════════════════════════════════════
# 進度 Dashboard（固定行覆寫）
# ══════════════════════════════════════════════════════════════════════════════

class _Progress:
    """簡單的單行進度列（不滾動）。"""
    def __init__(self, total: int):
        self.total   = total
        self.done    = 0
        self.success = 0
        self.failed  = 0
        self._lock   = threading.Lock()
        self._t0     = time.perf_counter()

    def update(self, ok: bool):
        with self._lock:
            self.done += 1
            if ok: self.success += 1
            else:  self.failed  += 1
            self._render()

    def _render(self):
        pct    = self.done / self.total * 100
        filled = int(pct / 5)
        bar    = (_c(chr(9608) * filled,        "green") +
                  _c(chr(9617) * (20 - filled), "dim"))
        elapsed = time.perf_counter() - self._t0
        eta     = ""
        if self.done > 0:
            rem = elapsed / self.done * (self.total - self.done)
            m, s = divmod(int(rem), 60)
            eta  = f"  ETA {m}m{s:02d}s"
        line = (f"\r  [{bar}] {pct:5.1f}%  "
                f"{self.done}/{self.total}  "
                f"{_c(f'✓{self.success}','green')}  "
                f"{_c(f'✗{self.failed}','red') if self.failed else ''}"
                f"{eta}   ")
        sys.stdout.write(line)
        sys.stdout.flush()

    def finish(self):
        elapsed = time.perf_counter() - self._t0
        sys.stdout.write("\n")
        sys.stdout.flush()
        return elapsed


# ══════════════════════════════════════════════════════════════════════════════
# 批次轉換主函式
# ══════════════════════════════════════════════════════════════════════════════

def batch_convert(input_dir: str,
                  output_dir: str,
                  fields: list | None = None,
                  n_workers: int = 4,
                  resume: bool = True):
    """
    掃描 input_dir 下所有 .npz，批次轉換為 .cube。

    input_dir  : 含有 .npz 的目錄（qsar_grid_maps/）
    output_dir : .cube 輸出目錄（可與 input_dir 相同）
    fields     : 要轉換的場，None = 全部
    n_workers  : 平行 worker 執行緒數（.cube 寫入是 I/O bound，用 thread 即可）
    resume     : True = 跳過已存在的 .cube（斷點續轉）
    """
    # ── 收集 npz 清單 ─────────────────────────────────────────────────────────
    npz_files = sorted([
        os.path.join(input_dir, f)
        for f in os.listdir(input_dir)
        if f.lower().endswith(".npz") and not f.startswith("_")
    ])

    if not npz_files:
        print(_c(f"  找不到任何 .npz 檔案於：{input_dir}", "red"))
        return

    n_total = len(npz_files)
    print(f"  找到 {_c(str(n_total), 'bold')} 個 .npz 檔案")

    # ── 斷點續轉：跳過已有全部 .cube 的分子 ──────────────────────────────────
    to_convert = []
    skipped    = 0
    target_fields = fields if fields else ALL_FIELDS

    for npz_path in npz_files:
        mol_name = os.path.splitext(os.path.basename(npz_path))[0]
        if resume:
            # 只要有任何一個目標場的 .cube 不存在就納入轉換
            existing = [
                os.path.exists(os.path.join(output_dir, f"{mol_name}_{f}.cube"))
                for f in target_fields
            ]
            # 若 npz 實際包含的場數未知，保守策略：只要有任一缺少就轉換
            if all(existing):
                skipped += 1
                continue
        to_convert.append(npz_path)

    if skipped:
        print(_c(f"  ⚙  斷點續轉：跳過 {skipped} 個已完成分子", "cyan"))

    if not to_convert:
        print(_c("  所有分子均已轉換完成。", "green"))
        return

    print(f"  待轉換    : {_c(str(len(to_convert)), 'bold')} 個")
    print(f"  輸出欄位  : {_c(', '.join(target_fields), 'dim')}")
    print(f"  Workers   : {n_workers}")
    print(f"  輸出目錄  : {_c(output_dir, 'cyan')}")
    print()

    # ── 平行轉換（ThreadPoolExecutor，I/O bound 用 thread 即可）──────────────
    from concurrent.futures import ThreadPoolExecutor, as_completed

    progress   = _Progress(len(to_convert))
    fail_list  = []   # (mol_name, reason)
    success_list = []

    def _task(npz_path):
        mol_name, n_written, err = convert_npz(npz_path, output_dir, fields)
        progress.update(ok=(err is None))
        return mol_name, n_written, err

    with ThreadPoolExecutor(max_workers=n_workers) as pool:
        futures = {pool.submit(_task, p): p for p in to_convert}
        for fut in as_completed(futures):
            mol_name, n_written, err = fut.result()
            if err:
                fail_list.append((mol_name, err))
            else:
                success_list.append((mol_name, n_written))

    elapsed = progress.finish()

    # ── 結果摘要 ──────────────────────────────────────────────────────────────
    total_cubes = sum(n for _, n in success_list)
    print(_hr("═"))
    print(_c("  轉換完成", "bold", "green"))
    print(_hr())
    print(f"  成功   : {_c(str(len(success_list)), 'green')} 個分子  "
          f"（共 {_c(str(total_cubes), 'cyan')} 個 .cube 檔案）")
    print(f"  跳過   : {_c(str(skipped), 'cyan')} 個（已存在）")
    print(f"  失敗   : {_c(str(len(fail_list)), 'red'  if fail_list else 'dim')} 個")
    print(f"  耗時   : {elapsed:.1f}s")
    print(f"  輸出   : {_c(os.path.abspath(output_dir), 'cyan')}")

    if fail_list:
        print(_hr())
        print(_c("  失敗清單：", "red"))
        for mol_name, reason in fail_list:
            print(f"    {_c(mol_name, 'yellow')}")
            for line in reason.strip().splitlines()[-3:]:
                print(f"      {_c(line, 'dim')}")

    print(_hr("═"))

    # DS 操作提示
    print(f"\n  {_c('Discovery Studio 載入步驟', 'bold')}")
    print(_hr("─"))
    print(f"  1. File → Open → {_c('all_aligned.sdf', 'yellow')}（全部對齊分子）")
    print(f"  2. File → Open → 選擇想查看的 {_c('*_perturb_steric.cube', 'yellow')}")
    print(f"       右鍵 isosurface → 正等值 {_c('+2.0', 'green')} 綠色 / 負等值 {_c('-2.0', 'yellow')} 黃色")
    print(f"  3. File → Open → 選擇 {_c('*_perturb_electro.cube', 'yellow')}")
    print(f"       正等值 {_c('+2.0', 'cyan')} 藍色 / 負等值 {_c('-2.0', 'red')} 紅色")
    print()


# ══════════════════════════════════════════════════════════════════════════════
# CLI 輔助
# ══════════════════════════════════════════════════════════════════════════════

def _prompt(label, default=None):
    hint = f"  [{_c(str(default), 'dim')}]" if default is not None else ""
    raw = input(f"  {_c('▸', 'cyan')} {label}{hint}: ").strip()
    return raw if raw else (str(default) if default is not None else "")

def _prompt_int(label, default, lo=1, hi=64):
    while True:
        raw = _prompt(label, default)
        try:
            v = int(raw)
            if lo <= v <= hi: return v
            print(_c(f"    請輸入 {lo}–{hi}", "red"))
        except ValueError:
            print(_c("    請輸入整數", "red"))

def _confirm(label, default=True):
    hint = "Y/n" if default else "y/N"
    raw = input(f"  {_c('▸', 'cyan')} {label} [{hint}]: ").strip().lower()
    return default if not raw else raw in ("y", "yes", "是")

def _print_banner():
    print("\n" + _hr("═"))
    print(_c("  NPZ → CUBE 批次轉換工具", "bold", "cyan"))
    print(_c("  npz_to_cube_batch.py  ·  qsar_grid_map.py 配套工具", "dim"))
    print(_hr("═") + "\n")


# ══════════════════════════════════════════════════════════════════════════════
# 主程式
# ══════════════════════════════════════════════════════════════════════════════

def main():
    if sys.platform == "win32":
        os.system("")

    parser = argparse.ArgumentParser(
        description="批次將 .npz 轉換為 .cube",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__)
    parser.add_argument("--input",   "-i", help="含 .npz 的目錄")
    parser.add_argument("--output",  "-o", help=".cube 輸出目錄（預設與 input 相同）")
    parser.add_argument("--fields",  "-f", nargs="+", choices=ALL_FIELDS,
                        help="要轉換的場（預設全部）")
    parser.add_argument("--workers", "-w", type=int, default=None,
                        help="平行 worker 數（預設 CPU 核心數的一半）")
    parser.add_argument("--no-resume", action="store_true",
                        help="不跳過已存在的 .cube，強制重新轉換")
    args = parser.parse_args()

    _print_banner()

    # ── 互動式補全 ────────────────────────────────────────────────────────────
    if sys.platform == "win32":
        os.system("")

    # input_dir
    if args.input:
        input_dir = args.input
    else:
        print(_c("  Step 1 / 3  ·  輸入目錄", "bold"))
        print(_hr())
        while True:
            input_dir = _prompt("含 .npz 的目錄", default="qsar_grid_maps")
            if os.path.isdir(input_dir): break
            print(_c(f"    找不到目錄：{input_dir}", "red"))

    # output_dir
    if args.output:
        output_dir = args.output
    else:
        print(f"\n  {_c('Step 2 / 3  ·  輸出目錄', 'bold')}")
        print(_hr())
        print(_c("  （直接 Enter = 與輸入目錄相同，.cube 與 .npz 放在一起）", "dim"))
        raw_out = _prompt("輸出目錄", default=input_dir)
        output_dir = raw_out if raw_out else input_dir

    # 場選擇
    if args.fields:
        fields = args.fields
    else:
        print(f"\n  {_c('Step 3 / 3  ·  選擇要轉換的場', 'bold')}")
        print(_hr())
        print(_c("  （直接 Enter = 全部轉換）", "dim"))
        for i, key in enumerate(ALL_FIELDS, 1):
            print(f"    {_c(str(i), 'cyan')}.  {_c(key, 'white'):<22}  "
                  f"{_c(FIELD_LABELS[key], 'dim')}")
        raw_fields = _prompt("輸入場編號（空白分隔，Enter=全部）", default="")
        if raw_fields.strip():
            chosen = []
            for token in raw_fields.split():
                try:
                    idx = int(token) - 1
                    if 0 <= idx < len(ALL_FIELDS):
                        chosen.append(ALL_FIELDS[idx])
                    else:
                        print(_c(f"  無效編號 {token}，忽略", "yellow"))
                except ValueError:
                    if token in ALL_FIELDS:
                        chosen.append(token)
                    else:
                        print(_c(f"  未知場名 {token}，忽略", "yellow"))
            fields = chosen if chosen else None
        else:
            fields = None

    # workers
    if args.workers:
        n_workers = args.workers
    else:
        cpu_avail = multiprocessing.cpu_count()
        n_workers = min(cpu_avail, 8)   # I/O bound，8 個通常足夠

    resume = not args.no_resume

    # ── 確認並執行 ────────────────────────────────────────────────────────────
    print()
    print(_hr())
    print(f"  輸入目錄  : {_c(os.path.abspath(input_dir), 'cyan')}")
    print(f"  輸出目錄  : {_c(os.path.abspath(output_dir), 'cyan')}")
    print(f"  轉換欄位  : {_c(', '.join(fields) if fields else '全部', 'green')}")
    print(f"  Workers   : {n_workers}")
    print(f"  斷點續轉  : {'是' if resume else '否（強制重轉）'}")
    print(_hr())

    if not _confirm("開始轉換？", default=True):
        print(_c("  已取消。", "dim"))
        sys.exit(0)

    print()
    batch_convert(
        input_dir  = input_dir,
        output_dir = output_dir,
        fields     = fields,
        n_workers  = n_workers,
        resume     = resume,
    )


if __name__ == "__main__":
    main()
