
import os, sys, time, math, csv, json, re, traceback
import multiprocessing
import threading
import numpy as np

ANGSTROM_TO_BOHR = 1.0 / 0.529177
VDW_RADII   = {1:1.20,6:1.70,7:1.55,8:1.52,9:1.47,15:1.80,16:1.80,17:1.75,35:1.85,53:1.98}
DEFAULT_VDW = 1.70
LJ_PROBE    = (0.086, 1.70)
LJ_PARAMS   = {1:(0.020,1.20),6:(0.086,1.70),7:(0.069,1.55),8:(0.060,1.52),
               9:(0.050,1.47),16:(0.274,1.80),17:(0.227,1.75),35:(0.320,1.85)}

# ---------------------------------------------------------------------------
# [新增] Z-score 標準化
#   對 Perturbation Field 輸出做 Z-score，使各工具 isovalue 可用統一標尺。
#   例：isovalue ±2.0 → 顯著貢獻區域（DS / Py3Dmol / PyMOL 均適用）。
# ---------------------------------------------------------------------------
def zscore_field(field, min_std=1e-6):
    """Z-score 標準化純量場。回傳 (z_field, mean, std)。"""
    mu  = float(field.mean())
    sig = float(field.std())
    if sig < min_std:
        return field - mu, mu, sig
    return (field - mu) / sig, mu, sig


# ---------------------------------------------------------------------------
# build_grid
#   [修改] 額外回傳幾何中心 centroid，供座標對齊驗證用。
# ---------------------------------------------------------------------------
def build_grid(coords, resolution=0.5, padding=4.0):
    centroid = coords.mean(axis=0)                           # [新增]
    lo = coords.min(axis=0) - padding
    hi = coords.max(axis=0) + padding
    nx = int(np.ceil((hi[0]-lo[0])/resolution)) + 1
    ny = int(np.ceil((hi[1]-lo[1])/resolution)) + 1
    nz = int(np.ceil((hi[2]-lo[2])/resolution)) + 1
    xs = np.linspace(lo[0], lo[0]+(nx-1)*resolution, nx)
    ys = np.linspace(lo[1], lo[1]+(ny-1)*resolution, ny)
    zs = np.linspace(lo[2], lo[2]+(nz-1)*resolution, nz)
    gx, gy, gz = np.meshgrid(xs, ys, zs, indexing="ij")
    return lo, (nx,ny,nz), np.diag([resolution]*3), gx, gy, gz, centroid


# ---------------------------------------------------------------------------
# write_cube
#   [修改] atom charge 欄固定輸出 0.0（DS / VMD / UCSF Chimera 標準）。
#   [修改] 函式簽名移除 charges 參數。
# ---------------------------------------------------------------------------
def write_cube(path, atomic_nums, atomic_coords, grid_data, origin, axes,
               title="QSAR", silent=False):
    """
    寫出 Gaussian cube 格式。
    silent=True 時不印任何輸出（批次模式使用）。
    """
    A2B      = ANGSTROM_TO_BOHR
    nx,ny,nz = grid_data.shape
    n_atoms  = len(atomic_nums)
    ox,oy,oz = origin * A2B
    with open(path, "w") as f:
        f.write(f"QSAR CONTRIBUTION FIELD: {title}\n")
        f.write("Generated by qsar_grid_map.py\n")
        f.write(f"{n_atoms:5d} {ox:12.6f} {oy:12.6f} {oz:12.6f}\n")
        for i in range(3):
            f.write(f"{[nx,ny,nz][i]:5d} "
                    f"{axes[i,0]*A2B:12.6f} "
                    f"{axes[i,1]*A2B:12.6f} "
                    f"{axes[i,2]*A2B:12.6f}\n")
        for anum, (x,y,z) in zip(atomic_nums, atomic_coords):
            f.write(f"{int(anum):5d} {0.0:12.6f} "
                    f"{x*A2B:12.6f} {y*A2B:12.6f} {z*A2B:12.6f}\n")
        flat = grid_data.ravel()
        for i in range(0, len(flat), 6):
            f.write(" ".join(f"{v:13.5E}" for v in flat[i:i+6]) + "\n")
    if not silent:
        print(f"  {os.path.basename(path):55s} ({os.path.getsize(path)//1024} KB)")


# ---------------------------------------------------------------------------
# write_npz / npz_to_cube
#   批次模式預設輸出：所有場資料打包成單一壓縮 .npz（約 1/5 cube 體積）
#   需要 .cube 時再用 npz_to_cube() 解包，可批次或單獨轉換。
# ---------------------------------------------------------------------------

def write_npz(path, mol_name, atomic_nums, atomic_coords,
              origin, axes, results, pred_pic50, resolution):
    """
    將一個分子的所有計算結果壓縮進單一 .npz 檔案。
    檔案結構：
      meta        : JSON 字串（mol_name, pred_pic50, resolution, origin, axes 等）
      atomic_nums : (N,) int16
      atomic_coords: (N,3) float32 Å
      saliency_total / saliency_electro / saliency_steric   : (nx,ny,nz) float32
      perturb_steric / perturb_electro                       : (nx,ny,nz) float32
      ig_total                                               : (nx,ny,nz) float32
    """
    arrays = {}
    arrays["atomic_nums"]   = atomic_nums.astype(np.int16)
    arrays["atomic_coords"] = atomic_coords.astype(np.float32)

    if "saliency" in results:
        s = results["saliency"]
        arrays["saliency_total"]  = s["total"].astype(np.float32)
        arrays["saliency_electro"]= s["electro"].astype(np.float32)
        arrays["saliency_steric"] = s["steric"].astype(np.float32)
    if "perturbation" in results:
        p = results["perturbation"]
        arrays["perturb_steric"]  = p["steric"].astype(np.float32)
        arrays["perturb_electro"] = p["electro"].astype(np.float32)
    if "ig" in results:
        arrays["ig_total"] = results["ig"]["grid"].astype(np.float32)

    meta = {
        "mol_name":   mol_name,
        "pred_pic50": float(pred_pic50),
        "resolution": float(resolution),
        "origin":     origin.tolist(),
        "axes":       axes.tolist(),
        "shape":      list(next(iter(arrays.values())).shape)
                      if arrays else [0,0,0],
        "baseline":   float(results["perturbation"]["baseline"])
                      if "perturbation" in results else None,
    }
    # meta 存為單元素 object array（npz 不直接支援 str）
    arrays["_meta"] = np.array([json.dumps(meta, ensure_ascii=False)], dtype=object)

    np.savez_compressed(path, **arrays)


def npz_to_cube(npz_path, output_dir=None, fields=None):
    """
    將 .npz 解包並輸出指定場的 .cube 檔案。

    npz_path  : .npz 檔路徑
    output_dir: 輸出目錄（預設與 npz 同目錄）
    fields    : list of str，可選：
                  'saliency_total', 'saliency_electro', 'saliency_steric',
                  'perturb_steric', 'perturb_electro', 'ig_total'
                None 表示輸出全部存在的場。

    回傳：輸出的 .cube 路徑清單。

    Windows 注意：使用 mmap_mode=None + 明確 close()，
    避免 memory-map handle 未釋放導致後續檔案操作失敗。
    """
    # mmap_mode=None：強制將全部資料載入記憶體，不保留檔案 handle
    npzfile = np.load(npz_path, allow_pickle=True, mmap_mode=None)
    try:
        meta = json.loads(str(npzfile["_meta"][0]))

        mol_name      = meta["mol_name"]
        origin        = np.array(meta["origin"])
        axes          = np.array(meta["axes"])
        atomic_nums   = npzfile["atomic_nums"].astype(int)
        atomic_coords = npzfile["atomic_coords"].astype(float)

        field_map = {
            "saliency_total":   f"Saliency Total:{mol_name}",
            "saliency_electro": f"Saliency Electrostatic:{mol_name}",
            "saliency_steric":  f"Saliency Steric:{mol_name}",
            "perturb_steric":   f"Perturbation Steric:{mol_name}",
            "perturb_electro":  f"Perturbation Electro:{mol_name}",
            "ig_total":         f"IG:{mol_name}",
        }
        available = [k for k in field_map if k in npzfile]
        to_export = fields if fields else available

        # 把需要的場資料先讀進 dict，之後關閉 npzfile 再寫 cube
        field_data = {}
        for key in to_export:
            if key in npzfile:
                field_data[key] = npzfile[key].astype(float)
    finally:
        npzfile.close()   # 明確釋放 handle（Windows 必須在此處關閉）

    if output_dir is None:
        output_dir = os.path.dirname(os.path.abspath(npz_path))
    os.makedirs(output_dir, exist_ok=True)

    out_paths = []
    for key in to_export:
        if key not in field_data:
            print(f"  [警告] {npz_path} 不含 '{key}' 場，跳過")
            continue
        cube_path = os.path.join(output_dir, f"{mol_name}_{key}.cube")
        write_cube(cube_path,
                   atomic_nums, atomic_coords,
                   field_data[key],
                   origin, axes,
                   title=field_map[key])
        out_paths.append(cube_path)

    print(f"  {mol_name} → {len(out_paths)} 個 .cube 檔案")
    return out_paths


# ---------------------------------------------------------------------------
# _smear_vectorised  [新增]
#   向量化 Gaussian smearing，取代所有方法內的 for-loop。
#   利用 (N_atoms, N_voxels) NumPy 廣播，RTX 5080 環境下 CPU 側亦可在
#   <1 s 內完成單分子 smearing；chunk_pts 控制峰值記憶體用量。
# ---------------------------------------------------------------------------
def _smear_vectorised(weights, coords, atomic_nums, gx, gy, gz,
                      sigma_scale=1.0, chunk_pts=200_000):
    """
    weights    : (N,) float — per-atom scalar contribution
    coords     : (N, 3) float Å
    atomic_nums: (N,) int
    返回 (nx,ny,nz) float32 field
    """
    pts = np.stack([gx.ravel(), gy.ravel(), gz.ravel()], axis=1)  # (V, 3)
    V   = pts.shape[0]
    out = np.zeros(V, dtype=np.float32)

    sigmas = np.array([VDW_RADII.get(int(a), DEFAULT_VDW) * sigma_scale
                       for a in atomic_nums], dtype=np.float32)
    w      = weights.astype(np.float32)

    active    = np.abs(w) >= 1e-9
    if not active.any():
        return out.reshape(gx.shape)
    coords_a  = coords[active].astype(np.float32)
    sigmas_a  = sigmas[active]
    w_a       = w[active]

    for start in range(0, V, chunk_pts):
        end   = min(start + chunk_pts, V)
        p     = pts[start:end]                              # (B, 3)
        d2    = ((p[:, None, :] - coords_a[None, :, :]) ** 2).sum(-1)  # (B, A)
        gauss = np.exp(-d2 / (2.0 * sigmas_a[None, :] ** 2))
        out[start:end] = (gauss * w_a[None, :]).sum(-1)

    return out.reshape(gx.shape)


# ---------------------------------------------------------------------------
# method_saliency
#   [修正] 梯度對象：pos → node features data.x
#   [修正] charge fallback：電負度估算 → np.zeros
#   [優化] smearing：for-loop → _smear_vectorised
# ---------------------------------------------------------------------------
def method_saliency(model, graph, device, gx, gy, gz, sigma_scale=1.0):
    """
    [效能優化]
    - AMP BF16 autocast：forward pass 走 Tensor Core
    - GradScaler：防止 BF16 梯度下溢
    - _smear_vectorised 三場平行化：用 ThreadPoolExecutor 同時計算
    """
    import torch
    from concurrent.futures import ThreadPoolExecutor

    model.eval()
    data  = graph.to(device)
    batch = data.batch if data.batch is not None else \
        torch.zeros(data.x.size(0), dtype=torch.long, device=device)
    ea    = getattr(data, "edge_attr", None)

    use_amp = (device.type == "cuda")

    x = data.x.detach().clone().float().requires_grad_(True)

    # 同 IG 的理由：Saliency 只讀梯度不更新參數，不需要 GradScaler。
    # autocast BF16 forward 後，leaf FP32 tensor 的 .grad 會由 PyTorch
    # 自動保持 FP32，直接讀取即可。
    with torch.amp.autocast(device_type=device.type,
                            dtype=torch.bfloat16, enabled=use_amp):
        out = model(x, data.pos, data.edge_index, batch, x=x, edge_attr=ea)
        if isinstance(out, dict): out = out["pic50"]

    out.sum().backward()

    contrib   = x.grad.data.norm(p=2, dim=1).cpu().numpy()
    coords    = data.pos.detach().cpu().numpy()
    atomic_n  = data.x[:, 0].long().cpu().numpy()
    charges_g = data.x[:, 8].cpu().numpy() if data.x.shape[1] >= 9 \
                else np.zeros(len(atomic_n))
    vols      = np.array([(4/3)*np.pi * VDW_RADII.get(int(a), DEFAULT_VDW)**3
                          for a in atomic_n])

    # 三個 smearing 場平行計算（CPU-bound，用執行緒池）
    print("    smearing (parallel)...", end="", flush=True)
    def _s_total():
        return _smear_vectorised(contrib, coords, atomic_n, gx, gy, gz, sigma_scale)
    def _s_electro():
        return _smear_vectorised(contrib * np.abs(charges_g), coords, atomic_n, gx, gy, gz, sigma_scale)
    def _s_steric():
        return _smear_vectorised(contrib * vols, coords, atomic_n, gx, gy, gz, sigma_scale)

    with ThreadPoolExecutor(max_workers=3) as pool:
        f_total   = pool.submit(_s_total)
        f_electro = pool.submit(_s_electro)
        f_steric  = pool.submit(_s_steric)
        total   = f_total.result()
        electro = f_electro.result()
        steric  = f_steric.result()
    print(" done")

    return contrib, charges_g, coords, atomic_n, total, electro, steric


# ---------------------------------------------------------------------------
# method_perturbation
#   [修正] probe 插入圖 → atom masking (zero-out)，消除孤立節點問題
#   [優化] Batch.from_data_list() 批次 forward，消除雙層 Python loop
#   [新增] 輸出前對立體場/靜電場分別做 Z-score 標準化
# ---------------------------------------------------------------------------
def method_perturbation(model, graph, device, gx, gy, gz,
                        probe_radius=1.2, batch_size=256):
    """
    [效能優化]
    1. occupied mask：Python for-loop → 純 NumPy 向量化（最大單點改善）
    2. 圖準備：data0.clone() per-voxel → 預先計算全部 mask，只在 batch 組裝時套用
    3. AMP BF16：forward pass 走 Tensor Core
    4. Pinned memory + 雙 CUDA stream：CPU 備料與 GPU 計算交錯（pipeline）
    5. 三次 eval_masked_batch 改為同一迴圈一次過備料、三路同時送出
    """
    import torch
    from torch_geometric.data import Batch

    model.eval()
    data0  = graph.to(device)
    ea0    = getattr(data0, "edge_attr", None)
    batch0 = data0.batch if data0.batch is not None else \
        torch.zeros(data0.x.size(0), dtype=torch.long, device=device)

    use_amp = (device.type == "cuda")

    # ── Baseline ────────────────────────────────────────────────────────────
    with torch.no_grad():
        with torch.amp.autocast(device_type=device.type,
                                dtype=torch.bfloat16, enabled=use_amp):
            out0 = model(data0.x, data0.pos, data0.edge_index, batch0,
                         x=data0.x, edge_attr=ea0)
            if isinstance(out0, dict): out0 = out0["pic50"]
        baseline = float(out0.float().mean().item())

    coords_np = data0.pos.cpu().numpy()           # (N_atoms, 3)
    atomic_n  = data0.x[:, 0].cpu().numpy()
    has_charge = data0.x.shape[1] >= 9

    pts   = np.stack([gx.ravel(), gy.ravel(), gz.ravel()], axis=1)  # (V, 3)
    n_pts = pts.shape[0]

    # ── 1. occupied mask：向量化，一次算完 ──────────────────────────────────
    #    原本：for i in range(N_atoms): dist = norm(pts - rc)  → O(V×N) Python loop
    #    現在：廣播 (V,3) vs (N,3) → (V,N) 距離矩陣，全 NumPy
    print("    計算佔用格點 (向量化)...", end="", flush=True)
    r_probes = np.array([probe_radius + VDW_RADII.get(int(a), DEFAULT_VDW) * 0.8
                         for a in atomic_n], dtype=np.float32)          # (N,)
    # 分塊避免峰值記憶體過大（V×N×3 fp32），chunk = 500k 格點
    chunk_v   = 500_000
    occupied  = np.zeros(n_pts, dtype=bool)
    for vs in range(0, n_pts, chunk_v):
        ve    = min(vs + chunk_v, n_pts)
        d2    = ((pts[vs:ve, None, :] - coords_np[None, :, :]) ** 2).sum(-1)  # (B,N)
        occupied[vs:ve] = (np.sqrt(d2) < r_probes[None, :]).any(axis=1)
    valid_mask = ~occupied
    valid_pts  = pts[valid_mask]
    n_valid    = valid_pts.shape[0]
    print(f" {n_valid:,} 有效格點 (跳過 {occupied.sum():,})")

    # ── 2. cutoff mask 矩陣預計算 ────────────────────────────────────────────
    #    每個有效格點 → 哪些原子在 cutoff 內 → 預存為 bool array，批次時直接索引
    cutoff = probe_radius + 1.5
    print("    預計算 cutoff mask...", end="", flush=True)
    # 同樣分塊
    atom_masks = np.zeros((n_valid, len(coords_np)), dtype=bool)
    for vs in range(0, n_valid, chunk_v):
        ve   = min(vs + chunk_v, n_valid)
        d2   = ((valid_pts[vs:ve, None, :] - coords_np[None, :, :]) ** 2).sum(-1)
        atom_masks[vs:ve] = np.sqrt(d2) <= cutoff
    print(" done")

    # ── 3. 核心：三路並行 batch forward（steric / electro+ / electro-）──────
    #    每個 batch 同時準備三份圖（mask=0 / charge×+1 / charge×-1），
    #    一次 GPU forward 出三個預測，省掉原本三次獨立迭代。
    #
    #    雙 CUDA stream：stream_a 跑 forward，同時 stream_b 在 CPU 準備下一個 batch
    #    （透過 threading + pinned memory tensor 實現）

    import threading
    from concurrent.futures import ThreadPoolExecutor

    n_batches = math.ceil(n_valid / batch_size)

    # 結果緩衝
    res_steric  = np.zeros(n_valid, dtype=np.float32)
    res_electro = np.zeros(n_valid, dtype=np.float32)   # dp - dn 最後再算

    # x_base：原始節點特徵的 CPU copy，供快速 clone
    x_cpu   = data0.x.cpu()
    pos_cpu = data0.pos.cpu()
    ei_cpu  = data0.edge_index.cpu()
    ea_cpu  = data0.edge_attr.cpu() if ea0 is not None else None

    stream_compute = torch.cuda.Stream() if use_amp else None

    def _build_triple_batch(start):
        """
        CPU 側：為 [start, start+batch_size) 的有效格點
        建立三份圖（steric / +charge / -charge），回傳 Batch 物件（仍在 CPU）。
        """
        end      = min(start + batch_size, n_valid)
        masks_b  = atom_masks[start:end]         # (B, N_atoms)
        graphs_s, graphs_p, graphs_n = [], [], []

        for bi in range(end - start):
            mask = masks_b[bi]

            # steric（mask=0）
            x_s = x_cpu.clone()
            x_s[mask] = 0.0
            d_s = data0.__class__(x=x_s, pos=pos_cpu,
                                  edge_index=ei_cpu,
                                  edge_attr=ea_cpu,
                                  batch=None)
            graphs_s.append(d_s)

            # electro +
            if has_charge and mask.any():
                x_p = x_cpu.clone(); x_p[mask, 8] *= 1.0   # charge_val = +1 (no-op, kept for clarity)
            else:
                x_p = x_cpu.clone(); x_p[mask] = 0.0
            d_p = data0.__class__(x=x_p, pos=pos_cpu,
                                  edge_index=ei_cpu,
                                  edge_attr=ea_cpu,
                                  batch=None)
            graphs_p.append(d_p)

            # electro -
            if has_charge and mask.any():
                x_n = x_cpu.clone(); x_n[mask, 8] *= -1.0
            else:
                x_n = x_cpu.clone(); x_n[mask] = 0.0
            d_n = data0.__class__(x=x_n, pos=pos_cpu,
                                  edge_index=ei_cpu,
                                  edge_attr=ea_cpu,
                                  batch=None)
            graphs_n.append(d_n)

        bs = Batch.from_data_list(graphs_s)
        bp = Batch.from_data_list(graphs_p)
        bn = Batch.from_data_list(graphs_n)
        return bs, bp, bn, end - start

    def _forward_triple(bs, bp, bn, C):
        """GPU 側：送入三份 Batch，回傳 (pred_s, pred_p, pred_n) numpy arrays。"""
        ctx = torch.cuda.stream(stream_compute) if stream_compute else _nullctx()
        with ctx:
            with torch.no_grad():
                with torch.amp.autocast(device_type=device.type,
                                        dtype=torch.bfloat16, enabled=use_amp):
                    def _infer(b):
                        b  = b.to(device, non_blocking=True)
                        ea = getattr(b, "edge_attr", None)
                        o  = model(b.x, b.pos, b.edge_index, b.batch,
                                   x=b.x, edge_attr=ea)
                        if isinstance(o, dict): o = o["pic50"]
                        o  = o.mean(dim=-1) if o.ndim > 1 else o
                        return (o.float() - baseline).cpu().numpy()
                    ps = _infer(bs)
                    pp = _infer(bp)
                    pn = _infer(bn)
        return ps, pp, pn

    # 雙 buffer pipeline：用執行緒池在 GPU 計算時預備下一個 CPU batch
    print("    三路擾動場計算（pipeline）：")
    with ThreadPoolExecutor(max_workers=2) as pool:
        # 預先準備第 0 個 batch
        future_cpu = pool.submit(_build_triple_batch, 0)

        for bi in range(n_batches):
            start = bi * batch_size
            end   = min(start + batch_size, n_valid)
            C     = end - start

            # 等待 CPU batch 備料完成
            bs, bp, bn, C = future_cpu.result()

            # 同時提交下一個 CPU batch 備料
            if bi + 1 < n_batches:
                future_cpu = pool.submit(_build_triple_batch, (bi + 1) * batch_size)

            # GPU forward
            ps, pp, pn = _forward_triple(bs, bp, bn, C)

            res_steric [start:end] = ps
            res_electro[start:end] = pp - pn   # ΔΔpIC50 electro

            pct = (bi + 1) / n_batches * 100
            print(f"\r    [{int(pct/5)*chr(9608)+(20-int(pct/5))*chr(9617)}] "
                  f"{pct:5.1f}%  batch {bi+1}/{n_batches}",
                  end="", flush=True)
    print()

    # ── 4. 填回完整格點並 Z-score ────────────────────────────────────────────
    sf_raw = np.zeros(n_pts, dtype=np.float32); sf_raw[valid_mask] = res_steric
    ef_raw = np.zeros(n_pts, dtype=np.float32); ef_raw[valid_mask] = res_electro
    sf_raw = sf_raw.reshape(gx.shape)
    ef_raw = ef_raw.reshape(gx.shape)

    sf, sf_mu, sf_std = zscore_field(sf_raw)
    ef, ef_mu, ef_std = zscore_field(ef_raw)
    print(f"    [Z-score] 立體場  mean={sf_mu:.4f}  std={sf_std:.4f}")
    print(f"    [Z-score] 靜電場  mean={ef_mu:.4f}  std={ef_std:.4f}")
    print(f"    → DS isovalue 建議：±2.0")

    return sf, ef, baseline


# ── 空 context manager（CPU fallback 用）──────────────────────────────────────
from contextlib import contextmanager
@contextmanager
def _nullctx():
    yield


# ---------------------------------------------------------------------------
# method_integrated_gradients
#   [修正] IG 對象：pos → node features data.x
#   [修正] baseline：centroid → zeros_like(x)
#   [優化] smearing → _smear_vectorised
# ---------------------------------------------------------------------------
def method_integrated_gradients(model, graph, device, gx, gy, gz,
                                n_steps=50, sigma_scale=1.0):
    """
    [效能優化]
    - AMP BF16：每步 forward 走 Tensor Core
    - GradScaler：防梯度下溢
    - integ 累積保持 FP32（unscale 後），數值穩定
    - smearing 與最後一步 backward 重疊：用執行緒提前啟動
    """
    import torch
    from concurrent.futures import ThreadPoolExecutor

    model.eval()
    data  = graph.to(device)
    ea    = getattr(data, "edge_attr", None)
    batch = data.batch if data.batch is not None else \
        torch.zeros(data.x.size(0), dtype=torch.long, device=device)

    use_amp = (device.type == "cuda")

    x_orig = data.x.detach().float()
    x_base = torch.zeros_like(x_orig)
    integ  = torch.zeros_like(x_orig)   # FP32 累積

    # 注意：IG 只需要讀梯度，完全不更新參數，不需要 GradScaler。
    # autocast 的 BF16 forward 後，PyTorch backward 會自動將梯度
    # 轉回 FP32 寫入 .grad，直接讀取即可，數值穩定且無 unscale_ 問題。
    for step in range(n_steps):
        alpha  = (step + 0.5) / n_steps
        x_step = (x_base + alpha * (x_orig - x_base)).detach().requires_grad_(True)

        with torch.amp.autocast(device_type=device.type,
                                dtype=torch.bfloat16, enabled=use_amp):
            out = model(x_step, data.pos, data.edge_index, batch,
                        x=x_step, edge_attr=ea)
            if isinstance(out, dict): out = out["pic50"]

        # backward 直接在 FP32 leaf tensor 上累積梯度
        out.sum().backward()

        with torch.no_grad():
            # .grad 已是 FP32（PyTorch autocast 保證 leaf grad 為 FP32）
            integ = integ + x_step.grad.detach()

        if (step + 1) % 10 == 0 or step == n_steps - 1:
            pct = (step + 1) / n_steps * 100
            print(f"\r    [{int(pct/5)*chr(9608)+(20-int(pct/5))*chr(9617)}] {pct:5.1f}%",
                  end="", flush=True)
    print()

    integ   /= n_steps
    ig_attr  = ((x_orig - x_base) * integ).norm(p=2, dim=1).cpu().numpy()
    coords   = data.pos.detach().cpu().numpy()
    atomic_n = data.x[:, 0].long().cpu().numpy()

    grid_ig = _smear_vectorised(ig_attr, coords, atomic_n, gx, gy, gz, sigma_scale)
    return ig_attr, grid_ig


# ---------------------------------------------------------------------------
# write_report  （原版保留，更新 DS isovalue 說明配合 Z-score 輸出）
# ---------------------------------------------------------------------------
def write_report(path, mol_name, pred_pic50, n_atoms, n_pts, results, resolution, elapsed):
    with open(path, "w", encoding="utf-8") as f:
        f.write("="*62+"\n")
        f.write("GNN-QSAR 貢獻場格點圖計算報告\n")
        f.write(f"分子名稱  : {mol_name}\n")
        f.write(f"預測pIC50 : {pred_pic50:.4f}\n")
        f.write(f"計算耗時  : {elapsed:.1f} 秒\n")
        f.write(f"格點解析度: {resolution} Angstrom\n")
        f.write(f"格點總數  : {n_pts:,}\n")
        f.write(f"分子原子數: {n_atoms}\n")
        f.write("="*62+"\n\n")
        if "saliency" in results:
            s    = results["saliency"]
            top5 = np.argsort(s["contrib"])[::-1][:5]
            f.write("[方法A Saliency]\n")
            f.write("  Top-5 重要原子：" + ", ".join(str(i) for i in top5) + "\n")
            f.write(f"  total 範圍: {s['total'].min():.4f}~{s['total'].max():.4f}\n\n")
        if "perturbation" in results:
            p = results["perturbation"]
            f.write("[方法B Perturbation Field  (Z-score 標準化)]\n")
            f.write(f"  基準 pIC50: {p['baseline']:.4f}\n")
            f.write(f"  立體場 Z: {p['steric'].min():.2f}~{p['steric'].max():.2f}  "
                    f"(建議 isovalue ±2.0)\n")
            f.write(f"  靜電場 Z: {p['electro'].min():.2f}~{p['electro'].max():.2f}  "
                    f"(建議 isovalue ±2.0)\n\n")
        if "ig" in results:
            g = results["ig"]
            f.write("[方法C Integrated Gradients]\n")
            f.write(f"  IG 格點範圍: {g['grid'].min():.4f}~{g['grid'].max():.4f}\n\n")
        f.write("="*62+"\n")
        f.write("Discovery Studio 操作（Perturbation 場已 Z-score）：\n")
        f.write("1. 開啟分子 .sdf  ← 使用 *_aligned.sdf（對齊後座標）\n")
        f.write("2. File->Open-> *_perturbation_steric.cube\n")
        f.write("   正等值 +2.0 (綠/立體有利)；負等值 -2.0 (黃/立體不利)\n")
        f.write("3. File->Open-> *_perturbation_electro.cube\n")
        f.write("   正等值 +2.0 (藍/靜電受體)；負等值 -2.0 (紅/靜電供體)\n")
        f.write("4. File->Open-> *_saliency_total.cube  Isovalue=max*0.35\n")
        f.write("5. File->Open-> *_ig_total.cube        Isovalue=max*0.35\n")
        f.write("\n[Py3Dmol / PyMOL] Perturbation 場同樣以 ±2.0 作為等值面標尺\n")
    print(f"  {os.path.basename(path):55s}")


# ---------------------------------------------------------------------------
# run_qsar_grid_map  （主流程）
#   [修改] build_grid 回傳值新增 centroid
#   [修改] write_cube 呼叫移除 charges 引數
#   [新增] aligned_mol 參數：若傳入對齊後的 RDKit Mol，自動輸出 _aligned.sdf
# ---------------------------------------------------------------------------
def run_qsar_grid_map(model, graph, device,
                      output_dir="qsar_grid_maps", mol_name="molecule",
                      resolution=0.5, padding=4.0,
                      methods=None, sigma_scale=1.0,
                      n_ig_steps=50, perturb_batch=256,
                      aligned_mol=None,
                      output_mode="npz",   # "npz" | "cube" | "both"
                      silent=False):
    """
    output_mode:
      "npz"  — 只輸出 .npz（預設，批次模式）
      "cube" — 只輸出 .cube
      "both" — 同時輸出 .npz 與 .cube
    silent:
      True  — 不印任何進度（批次模式由外層 dashboard 控制）
      False — 印完整進度（單分子模式）
    """
    import torch
    os.makedirs(output_dir, exist_ok=True)
    base = os.path.join(output_dir, mol_name)
    t0   = time.perf_counter()
    if methods is None: methods = ["saliency", "perturbation", "ig"]

    def _log(msg):
        if not silent: print(msg)

    coords_np = graph.pos.cpu().numpy()
    atomic_n  = graph.x[:, 0].long().cpu().numpy()
    n_atoms   = len(atomic_n)

    # CUDA context 暖機（只在第一次呼叫時實際耗時，之後為 no-op）
    if device.type == "cuda" and not getattr(run_qsar_grid_map, "_warmed_up", False):
        _ = torch.zeros(1, device=device)
        torch.cuda.synchronize()
        run_qsar_grid_map._warmed_up = True

    with torch.no_grad():
        model.eval()
        d  = graph.to(device)
        ea = getattr(d, "edge_attr", None)
        ba = d.batch if d.batch is not None else \
            torch.zeros(n_atoms, dtype=torch.long, device=device)
        o  = model(d.x, d.pos, d.edge_index, ba, x=d.x, edge_attr=ea)
        if isinstance(o, dict): o = o["pic50"]
        pred_pic50 = float(o.mean().item())

    _log(f"\n[QSAR格點圖] {mol_name}  原子:{n_atoms}  pIC50:{pred_pic50:.4f}  "
         f"解析度:{resolution}Å")

    origin, shape, axes, gx, gy, gz, centroid = build_grid(
        coords_np, resolution=resolution, padding=padding)
    nx, ny, nz = shape
    n_pts      = nx * ny * nz
    _log(f"  格點: {nx}×{ny}×{nz} = {n_pts:,}")
    _log(f"  幾何中心: ({centroid[0]:.2f}, {centroid[1]:.2f}, {centroid[2]:.2f}) Å")

    # 對齊 SDF：批次模式由外層 _AlignedSdfWriter 統一寫，單分子模式才在這裡寫
    if aligned_mol is not None and not silent:
        try:
            from rdkit.Chem import SDWriter
            sdf_out = base + "_aligned.sdf"
            w = SDWriter(sdf_out)
            w.write(aligned_mol)
            w.close()
            _log(f"  對齊座標 → {os.path.basename(sdf_out)}")
        except Exception as e:
            _log(f"  [警告] 無法寫出對齊 .sdf：{e}")

    results = {}

    if "saliency" in methods:
        _log("\n[A] Saliency 塗抹...")
        contrib, charges_g, coords_g, an_g, total, electro, steric = method_saliency(
            model, graph, device, gx, gy, gz, sigma_scale)
        results["saliency"] = {"contrib": contrib, "total": total,
                               "electro": electro, "steric": steric}

    if "perturbation" in methods:
        _log("\n[B] 擾動場 (Z-score 標準化)...")
        sg, eg, bl = method_perturbation(
            model, graph, device, gx, gy, gz, batch_size=perturb_batch)
        results["perturbation"] = {"steric": sg, "electro": eg, "baseline": bl}

    if "ig" in methods:
        _log("\n[C] Integrated Gradients...")
        ig_attr, grid_ig = method_integrated_gradients(
            model, graph, device, gx, gy, gz, n_ig_steps, sigma_scale)
        results["ig"] = {"attr": ig_attr, "grid": grid_ig}

    elapsed = time.perf_counter() - t0

    # ── 輸出 ────────────────────────────────────────────────────────────────
    if output_mode in ("npz", "both"):
        write_npz(base + ".npz", mol_name, atomic_n, coords_np,
                  origin, axes, results, pred_pic50, resolution)

    if output_mode in ("cube", "both"):
        if "saliency" in results:
            s = results["saliency"]
            write_cube(base+"_saliency_total.cube",
                       atomic_n, coords_np, s["total"],
                       origin, axes, f"Saliency Total:{mol_name}", silent=silent)
            write_cube(base+"_saliency_electrostatic.cube",
                       atomic_n, coords_np, s["electro"],
                       origin, axes, f"Saliency Electrostatic:{mol_name}", silent=silent)
            write_cube(base+"_saliency_steric.cube",
                       atomic_n, coords_np, s["steric"],
                       origin, axes, f"Saliency Steric:{mol_name}", silent=silent)
        if "perturbation" in results:
            p = results["perturbation"]
            write_cube(base+"_perturbation_steric.cube",
                       atomic_n, coords_np, p["steric"],
                       origin, axes, f"Perturbation Steric:{mol_name}", silent=silent)
            write_cube(base+"_perturbation_electro.cube",
                       atomic_n, coords_np, p["electro"],
                       origin, axes, f"Perturbation Electro:{mol_name}", silent=silent)
        if "ig" in results:
            write_cube(base+"_ig_total.cube",
                       atomic_n, coords_np, results["ig"]["grid"],
                       origin, axes, f"IG:{mol_name}", silent=silent)

    write_report(base+"_qsar_report.txt", mol_name, pred_pic50,
                 n_atoms, n_pts, results, resolution, elapsed)

    if not silent:
        print(f"\n[完成] {elapsed:.1f}s  -> {os.path.abspath(output_dir)}/")
        print("\n  Discovery Studio 建議：")
        if output_mode in ("cube", "both"):
            print(f"  ① 開啟對齊後的分子：{mol_name}_aligned.sdf")
            if "perturbation" in results:
                print(f"  ② {mol_name}_perturbation_steric.cube  正+2.0(綠)/負-2.0(黃)")
                print(f"  ③ {mol_name}_perturbation_electro.cube 正+2.0(藍)/負-2.0(紅)")
            if "saliency" in results:
                print(f"  ④ {mol_name}_saliency_total.cube       Isovalue=max×0.35")
            if "ig" in results:
                print(f"  ⑤ {mol_name}_ig_total.cube             Isovalue=max×0.35")
        else:
            print(f"  ① 開啟 all_aligned.sdf")
            print(f"  ② 用 npz_to_cube('{mol_name}.npz') 解包需要的場")

    return results, pred_pic50


# ===========================================================================
# 互動式 CLI 輔助函式
# ===========================================================================

# ANSI 顏色碼（Windows cmd 需先執行 `os.system("color")` 或用 colorama）
_C = {
    "reset": "\033[0m",  "bold":  "\033[1m",
    "cyan":  "\033[96m", "green": "\033[92m",
    "yellow":"\033[93m", "red":   "\033[91m",
    "dim":   "\033[2m",  "white": "\033[97m",
}

def _c(text, *keys):
    """套用 ANSI 色碼，若終端不支援則原樣回傳。"""
    if not sys.stdout.isatty():
        return text
    prefix = "".join(_C.get(k, "") for k in keys)
    return f"{prefix}{text}{_C['reset']}"

def _hr(char="─", width=62):
    return _c(char * width, "dim")

def _banner():
    lines = [
        "",
        _hr("═"),
        _c("  GNN-QSAR 貢獻場格點圖計算器", "bold", "cyan"),
        _c("  qsar_grid_map.py  ·  SchNet/EGNN  ·  RTX 5080 / CUDA 12.8", "dim"),
        _hr("═"),
        "",
    ]
    print("\n".join(lines))

def _prompt(label, default=None, validator=None):
    """
    帶預設值的單行提示。
    validator(value) → (bool, error_msg)；None 表示不驗證。
    """
    hint = f"  [{_c(str(default), 'dim')}]" if default is not None else ""
    while True:
        raw = input(f"  {_c('▸', 'cyan')} {label}{hint}: ").strip()
        value = raw if raw else (str(default) if default is not None else "")
        if not value:
            print(_c("    請輸入值。", "red")); continue
        if validator:
            ok, msg = validator(value)
            if not ok:
                print(_c(f"    {msg}", "red")); continue
        return value

def _prompt_path(label, must_exist=True, exts=None):
    """路徑提示，可選擇強制存在 + 副檔名驗證。"""
    def _v(v):
        if must_exist and not os.path.isfile(v):
            return False, f"找不到檔案：{v}"
        if exts and not any(v.lower().endswith(e) for e in exts):
            return False, f"檔案需為 {' / '.join(exts)} 格式"
        return True, ""
    return _prompt(label, validator=_v)

def _prompt_float(label, default, lo=None, hi=None):
    def _v(v):
        try:
            f = float(v)
        except ValueError:
            return False, "請輸入數字"
        if lo is not None and f < lo:
            return False, f"最小值 {lo}"
        if hi is not None and f > hi:
            return False, f"最大值 {hi}"
        return True, ""
    return float(_prompt(label, default=default, validator=_v))

def _prompt_int(label, default, lo=None, hi=None):
    def _v(v):
        try:
            i = int(v)
        except ValueError:
            return False, "請輸入整數"
        if lo is not None and i < lo:
            return False, f"最小值 {lo}"
        if hi is not None and i > hi:
            return False, f"最大值 {hi}"
        return True, ""
    return int(_prompt(label, default=default, validator=_v))

def _prompt_choice(label, choices, default=None):
    """
    choices: list of (key, description)
    回傳選中的 key。
    """
    print(f"\n  {_c(label, 'bold')}")
    for idx, (key, desc) in enumerate(choices, 1):
        marker = _c("●", "cyan") if (default and key == default) else _c("○", "dim")
        print(f"    {marker}  {idx}.  {_c(key, 'white')}  {_c(desc, 'dim')}")
    nums = list(range(1, len(choices)+1))
    def _v(v):
        if v.isdigit() and int(v) in nums:
            return True, ""
        # 允許直接輸入 key
        if v in [c[0] for c in choices]:
            return True, ""
        return False, f"請輸入 {nums[0]}~{nums[-1]} 或選項名稱"
    raw = _prompt("選擇", default=default, validator=_v)
    if raw.isdigit():
        return choices[int(raw)-1][0]
    return raw

def _prompt_multi(label, choices, defaults=None):
    """
    多選：空白分隔數字，或直接 Enter 接受預設。
    回傳選中的 key list。
    """
    defaults = defaults or [c[0] for c in choices]
    print(f"\n  {_c(label, 'bold')}")
    for idx, (key, desc) in enumerate(choices, 1):
        sel = _c("●", "green") if key in defaults else _c("○", "dim")
        print(f"    {sel}  {idx}.  {_c(key, 'white')}  {_c(desc, 'dim')}")
    print(_c("    （多選，空白分隔數字；直接 Enter = 全選）", "dim"))
    while True:
        raw = input(f"  {_c('▸', 'cyan')} 輸入: ").strip()
        if not raw:
            return defaults
        parts = raw.split()
        result = []
        ok = True
        for p in parts:
            if p.isdigit() and 1 <= int(p) <= len(choices):
                result.append(choices[int(p)-1][0])
            else:
                print(_c(f"    無效選項：{p}", "red")); ok = False; break
        if ok and result:
            return result

def _confirm(label, default=True):
    hint = "Y/n" if default else "y/N"
    raw = input(f"  {_c('▸', 'cyan')} {label} [{hint}]: ").strip().lower()
    if not raw:
        return default
    return raw in ("y", "yes", "是")

def _grid_preview(coords, resolution, padding):
    """計算並印出格點預覽，回傳 (nx, ny, nz, n_total)。"""
    lo = coords.min(axis=0) - padding
    hi = coords.max(axis=0) + padding
    nx = int(math.ceil((hi[0]-lo[0])/resolution)) + 1
    ny = int(math.ceil((hi[1]-lo[1])/resolution)) + 1
    nz = int(math.ceil((hi[2]-lo[2])/resolution)) + 1
    n  = nx * ny * nz
    size_mb = n * 4 / 1e6   # float32
    print(f"\n  {_c('格點預覽', 'bold')}")
    print(f"    維度  : {_c(f'{nx} × {ny} × {nz}', 'cyan')}")
    print(f"    總格點: {_c(f'{n:,}', 'cyan')}  (~{size_mb:.1f} MB / 場)")
    print(f"    解析度: {resolution} Å    padding: {padding} Å")
    return nx, ny, nz, n

def _summary_table(results, pred_pic50, elapsed, output_dir, mol_name):
    """計算完成後的結果摘要表。"""
    print("\n" + _hr("═"))
    print(_c("  結果摘要", "bold", "green"))
    print(_hr())
    print(f"  {'pIC50 預測':<20} {pred_pic50:.4f}")
    print(f"  {'計算耗時':<20} {elapsed:.1f} 秒")
    print(f"  {'輸出目錄':<20} {os.path.abspath(output_dir)}/")
    print(_hr())

    # 各方法結果
    rows = []
    if "saliency" in results:
        s    = results["saliency"]
        top1 = int(np.argmax(s["contrib"]))
        rows += [
            ("Saliency total",   f"max={s['total'].max():.4f}"),
            ("Saliency electro", f"max={s['electro'].max():.4f}"),
            ("Saliency steric",  f"max={s['steric'].max():.4f}   top atom={top1}"),
        ]
    if "perturbation" in results:
        p = results["perturbation"]
        rows += [
            ("Perturb steric  (Z)", f"{p['steric'].min():.2f} ~ {p['steric'].max():.2f}   baseline pIC50={p['baseline']:.4f}"),
            ("Perturb electro (Z)", f"{p['electro'].min():.2f} ~ {p['electro'].max():.2f}"),
        ]
    if "ig" in results:
        g = results["ig"]
        top1 = int(np.argmax(g["attr"]))
        rows += [
            ("IG total", f"{g['grid'].min():.4f} ~ {g['grid'].max():.4f}   top atom={top1}"),
        ]

    for name, val in rows:
        print(f"  {_c(name, 'cyan'):<30} {val}")

    print(_hr())
    print(_c("  Discovery Studio 載入建議", "bold"))
    step = 1
    print(f"  {step}. 開啟 {_c(mol_name+'_aligned.sdf', 'yellow')}"); step += 1
    if "perturbation" in results:
        print(f"  {step}. {mol_name}_perturbation_steric.cube   isovalue {_c('±2.0', 'green')} (Z-score)"); step += 1
        print(f"  {step}. {mol_name}_perturbation_electro.cube  isovalue {_c('±2.0', 'green')} (Z-score)"); step += 1
    if "saliency" in results:
        print(f"  {step}. {mol_name}_saliency_total.cube        isovalue {_c('max×0.35', 'green')}"); step += 1
    if "ig" in results:
        print(f"  {step}. {mol_name}_ig_total.cube              isovalue {_c('max×0.35', 'green')}"); step += 1
    print(_hr("═") + "\n")


# ===========================================================================
# main — 純互動式 CLI
# ===========================================================================
# ===========================================================================
# 批次輸入解析
# ===========================================================================

def _sanitize_mol_name(name: str, fallback: str) -> str:
    """
    將分子名稱轉為合法檔名（移除空白與特殊字元）。
    name 為空或全空白時使用 fallback。
    """
    name = (name or "").strip()
    if not name:
        return fallback
    # 保留字母、數字、底線、連字號、點；其餘換底線
    name = re.sub(r"[^\w.\-]", "_", name)
    # 避免 Windows 保留名稱（CON / PRN / AUX / NUL / COM1…COM9 / LPT1…LPT9）
    reserved = re.compile(r"^(CON|PRN|AUX|NUL|COM[1-9]|LPT[1-9])$", re.IGNORECASE)
    if reserved.match(name):
        name = "_" + name
    return name[:120]   # 限長，避免路徑過長


def _load_sdf_batch(sdf_path: str):
    """
    載入 SDF，回傳 list of (mol_name: str, mol: Chem.Mol, activity: float|None)。
    mol_name 取自 _Name property；若為空則用 mol_XXXXX 流水號。
    activity 取自 property 'activity' / 'pIC50' / 'pic50'（大小寫不分）。
    """
    from rdkit import Chem
    suppl = Chem.SDMolSupplier(sdf_path, removeHs=False, sanitize=True)
    records = []
    activity_keys = {"activity", "pic50", "pic_50", "pIC50"}
    for idx, mol in enumerate(suppl):
        if mol is None:
            print(_c(f"  [略過] SDF 第 {idx+1} 個條目解析失敗", "yellow"))
            continue
        raw_name = mol.GetProp("_Name") if mol.HasProp("_Name") else ""
        mol_name = _sanitize_mol_name(raw_name, f"mol_{idx+1:06d}")
        # 嘗試讀取活性值
        activity = None
        for pname in mol.GetPropsAsDict():
            if pname.lower().replace("-","_") in activity_keys:
                try:
                    activity = float(mol.GetProp(pname))
                except (ValueError, TypeError):
                    pass
                break
        records.append((mol_name, mol, activity))
    return records


def _load_csv_batch(csv_path: str, sdf_index: dict | None = None):
    """
    載入 CSV，回傳 list of (mol_name, mol_or_smiles, activity)。

    支援兩種模式：
      A) SMILES 欄位（欄名包含 'smiles'）→ 從 SMILES 建立 RDKit Mol（無 3D）
         後續 pipeline 會自動 EmbedMolecule + MMFF
      B) mol_name 欄位 + sdf_index → 從預載 SDF dict 查找 Mol

    欄名偵測（大小寫不分）：
      名稱欄: 'name' / 'mol_name' / 'id' / 'compound_id' / 'cmpd_id'
      SMILES欄: 'smiles' / 'canonical_smiles' / 'smi'
      活性欄: 'activity' / 'pic50' / 'pic_50' / 'pIC50' / 'value'
    """
    from rdkit import Chem

    name_keys     = {"name","mol_name","id","compound_id","cmpd_id"}
    smiles_keys   = {"smiles","canonical_smiles","smi"}
    activity_keys = {"activity","pic50","pic_50","value"}

    with open(csv_path, newline="", encoding="utf-8-sig") as fh:
        reader = csv.DictReader(fh)
        headers = [h.strip() for h in (reader.fieldnames or [])]

    # 欄名映射（不分大小寫）
    col_name     = next((h for h in headers if h.lower().replace("-","_") in name_keys),     None)
    col_smiles   = next((h for h in headers if h.lower().replace("-","_") in smiles_keys),   None)
    col_activity = next((h for h in headers if h.lower().replace("-","_") in activity_keys), None)

    if col_smiles is None and sdf_index is None:
        raise ValueError(
            "CSV 缺少 SMILES 欄（smiles/smi）且未提供 SDF 索引。\n"
            "  請確認 CSV 包含 smiles 欄，或同時提供 SDF 檔案。"
        )

    records = []
    with open(csv_path, newline="", encoding="utf-8-sig") as fh:
        reader = csv.DictReader(fh)
        for row_idx, row in enumerate(reader):
            raw_name = row.get(col_name, "").strip() if col_name else ""
            mol_name = _sanitize_mol_name(raw_name, f"mol_{row_idx+1:06d}")

            activity = None
            if col_activity:
                try:
                    activity = float(row[col_activity])
                except (ValueError, TypeError):
                    pass

            if col_smiles:
                smi = row[col_smiles].strip()
                if not smi:
                    print(_c(f"  [略過] CSV 第 {row_idx+2} 行：SMILES 為空", "yellow"))
                    continue
                mol = Chem.MolFromSmiles(smi)
                if mol is None:
                    print(_c(f"  [略過] CSV 第 {row_idx+2} 行 ({mol_name})：SMILES 無效", "yellow"))
                    continue
                records.append((mol_name, mol, activity))
            else:
                # 從 SDF 索引查找
                mol = sdf_index.get(mol_name)
                if mol is None:
                    print(_c(f"  [略過] 找不到 SDF 中對應分子：{mol_name}", "yellow"))
                    continue
                records.append((mol_name, mol, activity))

    return records


def _build_sdf_index(sdf_path: str) -> dict:
    """
    預載 SDF 所有分子，建立 {mol_name: mol} 字典，供 CSV 模式查找。
    """
    from rdkit import Chem
    index = {}
    suppl = Chem.SDMolSupplier(sdf_path, removeHs=False, sanitize=True)
    for idx, mol in enumerate(suppl):
        if mol is None:
            continue
        raw = mol.GetProp("_Name") if mol.HasProp("_Name") else ""
        name = _sanitize_mol_name(raw, f"mol_{idx+1:06d}")
        index[name] = mol
    return index


# ===========================================================================
# 3D 構象產生（SMILES → 3D Mol）
# ===========================================================================

def _smiles_to_3d(mol_2d, mol_name: str, n_confs: int = 1, seed: int = 42):
    """
    從 2D RDKit Mol（無 3D）產生 3D 構象並做 MMFF 最佳化。
    回傳 (mol_3d, None) 或 (None, error_str)。

    流程：
      1. AddHs
      2. EmbedMolecule（ETKDGv3，若失敗降級為 ETKDG，再失敗用 random）
      3. MMFFOptimizeMolecule（最多 2000 步）
    """
    from rdkit import Chem
    from rdkit.Chem import AllChem

    try:
        mol = Chem.AddHs(mol_2d)

        params = AllChem.ETKDGv3()
        params.randomSeed  = seed
        params.maxIterations = 1000
        params.numThreads  = 0     # 使用全部 CPU 核心

        ret = AllChem.EmbedMolecule(mol, params)
        if ret == -1:
            # 降級 ETKDG
            params2 = AllChem.EmbedParameters()
            params2.randomSeed = seed
            ret = AllChem.EmbedMolecule(mol, params2)
        if ret == -1:
            # 最後手段：隨機座標
            ret = AllChem.EmbedMolecule(mol, AllChem.ETKDG())
        if ret == -1:
            return None, f"{mol_name}: EmbedMolecule 完全失敗（結構可能太複雜）"

        ff_result = AllChem.MMFFOptimizeMolecule(mol, maxIters=2000)
        # ff_result: 0=已最佳化, 1=未收斂(仍可用), -1=無 FF
        if ff_result == -1:
            # 嘗試 UFF
            uff_result = AllChem.UFFOptimizeMolecule(mol, maxIters=2000)
            if uff_result == -1:
                return None, f"{mol_name}: MMFF 與 UFF 均無法建立力場"

        return mol, None

    except Exception as exc:
        return None, f"{mol_name}: 3D 建構例外 — {exc}"


# ===========================================================================
# 3D 分子前處理（含 MMFF minimization，適用 SDF 與 SMILES 來源）
# ===========================================================================

def _prepare_mol(mol_name: str, mol_raw, engine,
                 activity: float | None = None,
                 source: str = "sdf"):
    """
    輸入原始 Mol（可能是 2D SMILES 來源或已有 3D 的 SDF 分子），
    輸出 (mol_out, graph, label, error_str)。

    source: "sdf" | "smiles"
      - sdf    → 直接呼叫 engine._minimize_mmff
      - smiles → 先做 _smiles_to_3d，再呼叫 engine._minimize_mmff
    """
    from rdkit import Chem

    label = float(activity) if activity is not None else 0.0

    try:
        if source == "smiles":
            mol_3d, err = _smiles_to_3d(mol_raw, mol_name)
            if mol_3d is None:
                return None, None, label, err
        else:
            mol_3d = mol_raw   # SDF 分子已有 3D

        mol_out, _ = engine._minimize_mmff(mol_3d)
        if mol_out is None:
            return None, None, label, f"{mol_name}: engine._minimize_mmff 回傳 None"

        graph = engine.mol_to_graph(mol_out, label=label, smiles="")
        return mol_out, graph, label, None

    except Exception as exc:
        return None, None, label, f"{mol_name}: 前處理例外 — {traceback.format_exc(limit=3)}"


# ===========================================================================
# 斷點續算 Checkpoint
# ===========================================================================

_CKPT_FILE = "batch_checkpoint.json"

def _ckpt_load(output_dir: str) -> set:
    """
    載入已完成的 mol_name 集合。若無 checkpoint 檔則回傳空集合。
    """
    path = os.path.join(output_dir, _CKPT_FILE)
    if not os.path.isfile(path):
        return set()
    try:
        with open(path, encoding="utf-8") as fh:
            data = json.load(fh)
        return set(data.get("completed", []))
    except Exception:
        return set()


def _ckpt_save(output_dir: str, completed: set):
    """
    寫出 checkpoint，包含已完成分子名稱清單與時間戳。
    使用「先寫暫存再 rename」確保不產生半寫檔。
    """
    path     = os.path.join(output_dir, _CKPT_FILE)
    tmp_path = path + ".tmp"
    payload  = {
        "completed": sorted(completed),
        "count":     len(completed),
        "updated":   time.strftime("%Y-%m-%d %H:%M:%S"),
    }
    with open(tmp_path, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, ensure_ascii=False, indent=2)
    os.replace(tmp_path, path)


# ===========================================================================
# all_aligned.sdf 執行緒安全寫入器
# ===========================================================================

class _AlignedSdfWriter:
    """
    執行緒安全的累積 SDF 寫入器。
    使用 Lock 保護，允許主執行緒與子任務安全地 append。
    """
    def __init__(self, path: str):
        from rdkit.Chem import SDWriter
        self._path   = path
        self._writer = SDWriter(path)
        self._lock   = threading.Lock()
        self._count  = 0

    def write(self, mol):
        with self._lock:
            self._writer.write(mol)
            self._count += 1

    def close(self):
        with self._lock:
            self._writer.close()

    @property
    def count(self):
        with self._lock:
            return self._count


# ===========================================================================
# CPU 多核預處理 Worker
#   在獨立 Process 中平行執行 _prepare_mol（MMFF + graph 建構），
#   結果透過 multiprocessing.Queue 傳回主 process。
#   GPU forward 在主 process 執行（CUDA context 不跨 process）。
#   worker 數建議 = min(16, cpu_count // 2)，避免搶占 GPU thread 資源。
# ===========================================================================

def _worker_fn(task_queue, result_queue, engine_kwargs, source):
    """
    子 process worker：從 task_queue 取 (idx, mol_name, mol_raw, activity)，
    執行 _prepare_mol，把 (idx, mol_name, mol_out_sdf_block, graph_data, label, err)
    放入 result_queue。

    mol_out 以 SDF block string 傳回（跨 process 序列化 RDKit Mol）。
    graph_data 以 dict of numpy arrays 傳回（跨 process 序列化 PyG Data）。
    """
    # 每個 worker process 需要重新初始化 engine
    import sys, os
    sys.path.insert(0, engine_kwargs["model_dir"])
    from gpu_qsar_engine import GpuQsarEngine, DataConfig
    import dataclasses

    data_cfg = DataConfig(**engine_kwargs["data_cfg"])
    engine   = GpuQsarEngine(data_cfg)

    from rdkit import Chem
    from rdkit.Chem import SDWriter
    import io

    while True:
        task = task_queue.get()
        if task is None:   # sentinel
            break
        idx, mol_name, mol_raw_block, is_smiles, activity = task
        try:
            # 還原 mol_raw
            if is_smiles:
                mol_raw = Chem.MolFromSmiles(mol_raw_block)
                src = "smiles"
            else:
                mol_raw = Chem.MolFromMolBlock(mol_raw_block, removeHs=False)
                src = "sdf"

            mol_out, graph, label, err = _prepare_mol(
                mol_name, mol_raw, engine, activity=activity, source=src)

            if mol_out is None:
                result_queue.put((idx, mol_name, None, None, label, err))
                continue

            # 序列化 mol_out → SDF block string
            sio = io.StringIO()
            w   = SDWriter(sio)
            w.write(mol_out)
            w.flush()
            mol_sdf_block = sio.getvalue()

            # 序列化 graph → dict of numpy（避免 PyG Data pickle 問題）
            graph_dict = {
                "x":          graph.x.numpy(),
                "pos":        graph.pos.numpy(),
                "edge_index": graph.edge_index.numpy(),
                "edge_attr":  graph.edge_attr.numpy() if graph.edge_attr is not None else None,
            }
            result_queue.put((idx, mol_name, mol_sdf_block, graph_dict, label, None))

        except Exception as exc:
            result_queue.put((idx, mol_name, None, None,
                              activity or 0.0, traceback.format_exc(limit=3)))


def _graph_from_dict(graph_dict, device):
    """將 worker 傳回的 dict 重建為 PyG Data 物件並移到 device。"""
    import torch
    from torch_geometric.data import Data
    x  = torch.from_numpy(graph_dict["x"]).float()
    pos= torch.from_numpy(graph_dict["pos"]).float()
    ei = torch.from_numpy(graph_dict["edge_index"]).long()
    ea = torch.from_numpy(graph_dict["edge_attr"]).float() \
         if graph_dict["edge_attr"] is not None else None
    return Data(x=x, pos=pos, edge_index=ei, edge_attr=ea).to(device)


def _mol_from_sdf_block(sdf_block):
    """從 SDF block string 重建 RDKit Mol。"""
    from rdkit import Chem
    return Chem.MolFromMolBlock(sdf_block, removeHs=False)


def _mol_to_block(mol, is_smiles, mol_raw):
    """將 mol_raw 序列化為可跨 process 傳輸的格式。"""
    if is_smiles:
        from rdkit import Chem
        return Chem.MolToSmiles(mol_raw)
    else:
        from rdkit.Chem import SDWriter
        import io
        sio = io.StringIO()
        w   = SDWriter(sio)
        w.write(mol_raw)
        w.flush()
        return sio.getvalue()


# ===========================================================================
# Dashboard 顯示引擎
#   使用 ANSI escape code 在固定區域覆寫，不滾動螢幕。
#   佔用固定 8 行，批次全程只更新這 8 行。
# ===========================================================================

class _Dashboard:
    """
    固定 8 行的批次進度 dashboard。
    呼叫 init() 後使用 update() 更新，結束呼叫 finalize()。

    行配置：
      行 0: 標題列
      行 1: 總進度條
      行 2: ETA / 速度
      行 3: 當前分子名稱 + 階段
      行 4: 當前分子內部進度條（perturb / IG）
      行 5: 統計（✓ / ✗ / ⊘）
      行 6: GPU 備忘
      行 7: 空行（緩衝）
    """
    LINES = 8

    def __init__(self):
        self._init_done  = False
        self._last_lines = [""] * self.LINES
        self._lock       = threading.Lock()

    def init(self, n_total: int, output_dir: str):
        self.n_total    = n_total
        self.output_dir = output_dir
        # 印出初始佔位行
        print("\n" * self.LINES, end="")
        self._init_done = True
        self.update(0, 0, 0, 0, 0.0, "", "")

    def _move_up(self, n):
        return f"\033[{n}A"

    def _erase_line(self):
        return "\033[2K\r"

    def update(self, done: int, success: int, skipped: int, failed: int,
               elapsed: float, mol_name: str, stage: str,
               inner_pct: float = -1.0):
        """
        done       : 已處理分子數（含跳過）
        inner_pct  : 當前分子內部進度 0–100，-1 表示不顯示
        """
        if not self._init_done:
            return
        with self._lock:
            n   = self.n_total
            pct = done / n * 100 if n else 0
            bar_w = 30
            filled = int(pct / 100 * bar_w)
            bar = _c(chr(9608) * filled, "green") + _c(chr(9617) * (bar_w - filled), "dim")

            # ETA
            eta_str = ""
            speed   = ""
            if done > 0 and elapsed > 0:
                spm = elapsed / done
                rem = spm * (n - done)
                m, s = divmod(int(rem), 60)
                h, m = divmod(m, 60)
                eta_str = f"ETA {h}h{m:02d}m{s:02d}s" if h else f"ETA {m}m{s:02d}s"
                speed   = f"{spm:.1f}s/mol"

            # 內部進度條
            if inner_pct >= 0:
                iw = 20
                if_filled = int(inner_pct / 100 * iw)
                inner_bar = (_c(chr(9608) * if_filled, "cyan") +
                             _c(chr(9617) * (iw - if_filled), "dim"))
                stage_line = f"  {_c(mol_name[:40], 'yellow')}  [{inner_bar}] {inner_pct:5.1f}%  {_c(stage, 'dim')}"
            else:
                stage_line = (f"  {_c(mol_name[:40], 'yellow')}  "
                              f"{_c(stage, 'dim')}" if mol_name else "")

            lines = [
                f"  {_c('GNN-QSAR 批次計算', 'bold', 'cyan')}  →  {_c(self.output_dir, 'dim')}",
                f"  [{bar}] {pct:5.1f}%  {done}/{n}",
                f"  {_c(eta_str, 'cyan')}  {_c(speed, 'dim')}",
                stage_line,
                f"  {_c('─'*58, 'dim')}",
                (f"  {_c('✓', 'green')} {success}  "
                 f"{_c('✗', 'red')} {failed}  "
                 f"{_c('⊘', 'cyan')} {skipped} 跳過  "
                 f"{'  ' + _c('有失敗，詳見 batch_summary.txt', 'yellow') if failed else ''}"),
                "",
                "",
            ]

            # 上移並覆寫
            out = self._move_up(self.LINES)
            for line in lines:
                out += self._erase_line() + line + "\n"
            sys.stdout.write(out)
            sys.stdout.flush()
            self._last_lines = lines

    def log_error(self, mol_name: str, reason: str):
        """在 dashboard 上方印出錯誤（不破壞 dashboard）。"""
        with self._lock:
            # 先跳到 dashboard 上方
            sys.stdout.write(self._move_up(self.LINES))
            sys.stdout.write(self._erase_line())
            print(_c(f"  ✗ {mol_name}: {reason[:80]}", "red"))
            # 重印 dashboard
            out = ""
            for line in self._last_lines:
                out += self._erase_line() + line + "\n"
            sys.stdout.write(out)
            sys.stdout.flush()

    def _update_stage(self, mol_name: str, stage: str, inner_pct: float):
        """只更新 stage 行（由 method_* 函式呼叫）。"""
        with self._lock:
            iw = 20
            if_filled = int(inner_pct / 100 * iw)
            inner_bar = (_c(chr(9608) * if_filled, "cyan") +
                         _c(chr(9617) * (iw - if_filled), "dim"))
            stage_line = (f"  {_c(mol_name[:40], 'yellow')}  "
                          f"[{inner_bar}] {inner_pct:5.1f}%  {_c(stage, 'dim')}")
            # 只覆寫第 3 行（從底部數 LINES-1-3 行上移）
            up = self.LINES - 3
            out = f"\033[{up}A" + "\033[2K\r" + stage_line + "\n"
            # 重新移回底部
            out += f"\033[{up - 1}B"
            sys.stdout.write(out)
            sys.stdout.flush()
            self._last_lines[3] = stage_line

    def finalize(self):
        """結束後讓游標停在 dashboard 下方。"""
        print()


# 全域 dashboard 實例（main() 使用，方法函式透過此實例回報內部進度）
_DASHBOARD = None


def _dash_update_inner(mol_name: str, stage: str, pct: float):
    """供 method_* 函式呼叫，更新當前分子的內部進度。"""
    if _DASHBOARD is not None:
        # 不知道 done/success 等，只更新 stage 行
        _DASHBOARD._update_stage(mol_name, stage, pct)


# ===========================================================================
# 批次摘要報告（不變，只微調）
# ===========================================================================

def _write_batch_summary(output_dir: str,
                          records_total: int,
                          success_list: list,
                          skip_list:    list,
                          fail_list:    list,
                          elapsed:      float):
    """
    在 output_dir 下寫出 batch_summary.txt。
    success_list: list of (mol_name, pred_pic50)
    skip_list:    list of mol_name（checkpoint 跳過）
    fail_list:    list of (mol_name, reason)
    """
    path = os.path.join(output_dir, "batch_summary.txt")
    with open(path, "w", encoding="utf-8") as f:
        f.write("=" * 70 + "\n")
        f.write("GNN-QSAR 批次計算摘要\n")
        f.write(f"時間       : {time.strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write(f"輸出目錄   : {os.path.abspath(output_dir)}\n")
        f.write(f"總耗時     : {elapsed:.1f} 秒 ({elapsed/60:.1f} 分鐘)\n")
        f.write("=" * 70 + "\n\n")
        f.write(f"輸入分子數 : {records_total}\n")
        f.write(f"成功完成   : {len(success_list)}\n")
        f.write(f"略過(續算) : {len(skip_list)}\n")
        f.write(f"失敗       : {len(fail_list)}\n\n")

        if success_list:
            f.write("-" * 70 + "\n")
            f.write("成功分子與預測 pIC50：\n")
            for mol_name, pic50 in success_list:
                f.write(f"  {mol_name:<60} {pic50:.4f}\n")
            f.write("\n")

        if skip_list:
            f.write("-" * 70 + "\n")
            f.write("略過分子（已在前次計算完成）：\n")
            for mol_name in skip_list:
                f.write(f"  {mol_name}\n")
            f.write("\n")

        if fail_list:
            f.write("-" * 70 + "\n")
            f.write("失敗分子與原因：\n")
            for mol_name, reason in fail_list:
                f.write(f"  [{mol_name}]\n    {reason}\n\n")

        f.write("=" * 70 + "\n")
    print(f"\n  批次摘要 → {os.path.basename(path)}")


# ===========================================================================
# main — 互動式 CLI（支援單分子 / SDF 批次 / CSV 批次）
# ===========================================================================

def main():
    # ── 啟用 Windows ANSI（若在 cmd/PowerShell 執行）
    if sys.platform == "win32":
        os.system("")

    _banner()

    # ── Step 1：模型與輸入 ──────────────────────────────────────────────────
    print(_c("  Step 1 / 6  ·  模型與輸入模式", "bold"))
    print(_hr())

    model_path = _prompt_path("模型檔路徑 (.pt)", exts=[".pt", ".pth"])
    output_dir = _prompt("輸出目錄", default="qsar_grid_maps")

    # 輸入模式選擇
    print(f"\n  {_c('輸入模式', 'bold')}")
    for i, (key, desc) in enumerate([
        ("sdf",      "單一 SDF 檔（1 個分子）"),
        ("sdf_batch","SDF 批次（多個分子）"),
        ("csv_smiles","CSV + SMILES 欄位（從頭建 3D）"),
        ("csv_sdf",   "CSV + SDF 索引（CSV 提供名稱與活性，SDF 提供結構）"),
    ], 1):
        print(f"    {_c(str(i), 'cyan')}.  {_c(key, 'white')}  {_c(desc, 'dim')}")

    input_mode_idx = _prompt_int("選擇模式", default=2, lo=1, hi=4)
    input_mode = ["sdf", "sdf_batch", "csv_smiles", "csv_sdf"][input_mode_idx - 1]
    print(f"  已選  : {_c(input_mode, 'green')}")

    # 根據模式詢問路徑
    sdf_path = csv_path = None
    if input_mode in ("sdf", "sdf_batch"):
        sdf_path = _prompt_path("SDF 路徑 (.sdf)", exts=[".sdf"])
    elif input_mode == "csv_smiles":
        csv_path = _prompt_path("CSV 路徑 (.csv)", exts=[".csv"])
    elif input_mode == "csv_sdf":
        csv_path = _prompt_path("CSV 路徑 (.csv)", exts=[".csv"])
        sdf_path = _prompt_path("SDF 路徑 (.sdf，提供結構）", exts=[".sdf"])

    # ── Step 2：載入模型 ────────────────────────────────────────────────────
    print(f"\n  {_c('Step 2 / 6  ·  載入模型', 'bold')}")
    print(_hr())
    import torch
    sys.path.insert(0, os.path.dirname(os.path.abspath(model_path)))
    try:
        from gpu_qsar_engine import SchNetQSAR, GpuQsarEngine, DataConfig, TrainConfig
        import dataclasses
    except ImportError:
        print(_c("  錯誤：找不到 gpu_qsar_engine.py，請確認與模型同目錄。", "red"))
        sys.exit(1)

    cuda_ok  = torch.cuda.is_available()
    device   = torch.device("cuda" if cuda_ok else "cpu")
    gpu_name = torch.cuda.get_device_name(0) if cuda_ok else "N/A"
    print(f"  裝置  : {_c(str(device).upper(), 'cyan')}  {_c(gpu_name, 'dim')}")

    try:
        ckpt      = torch.load(model_path, map_location=device, weights_only=False)
        train_cfg = TrainConfig(**{k: v for k, v in ckpt["train_cfg"].items()
                                   if k in {f.name for f in dataclasses.fields(TrainConfig)}})
        model     = SchNetQSAR(train_cfg).to(device)
        model.load_state_dict(ckpt["model_state"])
        model.eval()
        print(f"  模型  : {_c('載入成功', 'green')}  ({os.path.basename(model_path)})")
    except Exception as e:
        print(_c(f"  模型載入失敗：{e}", "red")); sys.exit(1)

    try:
        data_cfg = DataConfig(**{k: v for k, v in ckpt["data_cfg"].items()
                                 if k in {f.name for f in dataclasses.fields(DataConfig)}})
        engine = GpuQsarEngine(data_cfg)
    except Exception as e:
        print(_c(f"  DataConfig / GpuQsarEngine 初始化失敗：{e}", "red")); sys.exit(1)

    # ── Step 3：解析輸入分子 ────────────────────────────────────────────────
    print(f"\n  {_c('Step 3 / 6  ·  解析輸入分子', 'bold')}")
    print(_hr())

    os.makedirs(output_dir, exist_ok=True)

    try:
        if input_mode == "sdf":
            records = _load_sdf_batch(sdf_path)
            if not records:
                print(_c("  SDF 中沒有可讀取的分子。", "red")); sys.exit(1)
            # 單分子模式：只取第一個
            records = records[:1]
            source  = "sdf"
            print(f"  SDF 模式（單分子）：{_c(records[0][0], 'yellow')}")

        elif input_mode == "sdf_batch":
            records = _load_sdf_batch(sdf_path)
            source  = "sdf"
            print(f"  SDF 批次：讀取到 {_c(str(len(records)), 'cyan')} 個分子")
            if not records:
                print(_c("  SDF 中沒有可讀取的分子。", "red")); sys.exit(1)

        elif input_mode == "csv_smiles":
            records = _load_csv_batch(csv_path, sdf_index=None)
            source  = "smiles"
            print(f"  CSV+SMILES：讀取到 {_c(str(len(records)), 'cyan')} 筆記錄")
            if not records:
                print(_c("  CSV 中沒有有效記錄。", "red")); sys.exit(1)

        elif input_mode == "csv_sdf":
            print("  建立 SDF 索引中…", end="", flush=True)
            sdf_index = _build_sdf_index(sdf_path)
            print(f" {len(sdf_index)} 個結構")
            records = _load_csv_batch(csv_path, sdf_index=sdf_index)
            source  = "sdf"
            print(f"  CSV+SDF：配對到 {_c(str(len(records)), 'cyan')} 筆記錄")
            if not records:
                print(_c("  無有效配對分子。", "red")); sys.exit(1)

    except Exception as e:
        print(_c(f"  輸入解析失敗：{e}", "red")); sys.exit(1)

    n_total = len(records)
    print(f"  合計   : {_c(str(n_total), 'bold')} 個分子待處理")

    # 斷點續算：告知跳過數量
    completed_set = _ckpt_load(output_dir)
    n_resume      = sum(1 for (nm, _, _) in records if nm in completed_set)
    if n_resume:
        print(_c(f"  ⚙  偵測到 checkpoint：{n_resume} 個已完成，將跳過重算", "cyan"))

    # ── Step 4：選擇計算方法 ────────────────────────────────────────────────
    print(f"\n  {_c('Step 4 / 6  ·  選擇計算方法', 'bold')}")
    print(_hr())
    methods = _prompt_multi(
        "計算方法（可多選）",
        choices=[
            ("saliency",     "Saliency Map        — 快速，∂output/∂node_feat，3 個 .cube"),
            ("perturbation", "Perturbation Field   — 較慢，ΔΔpIC50 / voxel，Z-score 輸出"),
            ("ig",           "Integrated Gradients — 中速，零基線路徑積分，1 個 .cube"),
        ],
        defaults=["saliency", "perturbation", "ig"],
    )
    print(f"  已選  : {_c(', '.join(methods), 'green')}")

    # ── Step 5：格點設定（以第一個可用分子預覽）──────────────────────────
    print(f"\n  {_c('Step 5 / 6  ·  格點設定', 'bold')}")
    print(_hr())

    # 找第一個未跳過的分子來做格點預覽
    preview_mol_name = preview_coords = None
    for (nm, mol_raw, act) in records:
        if nm in completed_set:
            continue
        _mol_out, _graph, _, _err = _prepare_mol(nm, mol_raw, engine,
                                                  activity=act, source=source)
        if _mol_out is not None:
            preview_mol_name = nm
            preview_coords   = _graph.pos.cpu().numpy()
            n_atoms_preview  = _graph.x.shape[0]
            break

    if preview_coords is None:
        # 所有分子都在 checkpoint 或全部失敗
        if n_resume == n_total:
            print(_c("  所有分子均已在 checkpoint 中完成，無需重算。", "cyan"))
            sys.exit(0)
        print(_c("  無法取得預覽分子（前處理皆失敗）。", "red")); sys.exit(1)

    print(f"  格點預覽以分子 {_c(preview_mol_name, 'yellow')} 為基準 ({n_atoms_preview} atoms)")
    print(_c("  注意：批次模式下每個分子會依自身原子座標各自建立格點。", "dim"))

    while True:
        resolution = _prompt_float("解析度 (Å)", default=0.5, lo=0.1, hi=2.0)
        padding    = _prompt_float("Padding (Å)", default=4.0, lo=1.0, hi=10.0)
        nx, ny, nz, n_pts_est = _grid_preview(preview_coords, resolution, padding)

        if n_pts_est > 8_000_000:
            print(_c(f"  ⚠  估計格點數 {n_pts_est:,} 超過 800 萬。", "yellow"))
        if n_total > 100 and n_pts_est > 4_000_000:
            total_gb_est = n_pts_est * 4 / 1e9 * len(methods) * n_total
            print(_c(f"  ⚠  {n_total} 個分子 × {len(methods)} 方法，估計磁碟 "
                     f"~{total_gb_est:.1f} GB，請確認空間足夠。", "yellow"))
        if _confirm("確認格點設定並繼續？", default=True):
            break
        print(_c("  → 重新設定格點參數", "dim"))

    # ── 進階參數（加入 CPU workers + 輸出格式）───────────────────────────────
    print(f"\n  {_c('進階參數', 'bold', 'dim')}  （直接 Enter 使用預設值）")
    sigma_scale   = _prompt_float("Gaussian sigma 縮放", default=1.0, lo=0.1, hi=5.0)
    n_ig_steps    = 50
    perturb_batch = 256
    if "ig" in methods:
        n_ig_steps = _prompt_int("IG 積分步數", default=50, lo=10, hi=500)
    if "perturbation" in methods:
        perturb_batch = _prompt_int("Perturbation batch size", default=256, lo=16, hi=2048)

    # CPU worker 數
    cpu_avail  = multiprocessing.cpu_count()
    n_workers  = _prompt_int(
        f"CPU 前處理 worker 數（可用 {cpu_avail} 核）",
        default=min(12, cpu_avail // 2), lo=1, hi=cpu_avail)

    # 輸出格式
    print(f"\n  {_c('輸出格式', 'bold')}")
    for i, (key, desc) in enumerate([
        ("npz",  "僅 .npz 壓縮（預設，~1/5 體積，需時再轉 .cube）"),
        ("cube", "僅 .cube（直接用 DS / VMD 開啟）"),
        ("both", "同時輸出 .npz 與 .cube"),
    ], 1):
        print(f"    {_c(str(i), 'cyan')}.  {_c(key, 'white')}  {_c(desc, 'dim')}")
    output_mode = ["npz", "cube", "both"][_prompt_int("選擇", default=1, lo=1, hi=3) - 1]
    print(f"  已選  : {_c(output_mode, 'green')}")

    # ── Step 6：最終確認 ────────────────────────────────────────────────────
    print(f"\n  {_c('Step 6 / 6  ·  確認執行', 'bold')}")
    print(_hr())
    print(f"  分子數    : {_c(str(n_total), 'bold')}  "
          f"（待算 {n_total - n_resume}，續算跳過 {n_resume}）")
    print(f"  方法      : {_c(', '.join(methods), 'green')}")
    print(f"  格點估計  : {nx}×{ny}×{nz} = {n_pts_est:,}  ({resolution} Å，以預覽分子計）")
    print(f"  CPU worker: {_c(str(n_workers), 'cyan')} 個平行前處理")
    print(f"  輸出格式  : {_c(output_mode, 'cyan')}")
    print(f"  輸出目錄  : {_c(output_dir, 'cyan')}")
    print(_hr())

    if not _confirm("開始計算？", default=True):
        print(_c("  已取消。", "dim")); sys.exit(0)

    # ── 批次執行（CPU worker pool + dashboard）──────────────────────────────
    import torch
    from rdkit import Chem
    from rdkit.Chem import SDWriter

    # engine 序列化資訊（傳給 worker process）
    import dataclasses as _dc
    engine_kwargs = {
        "model_dir": os.path.dirname(os.path.abspath(model_path)),
        "data_cfg":  {f.name: getattr(data_cfg, f.name)
                      for f in _dc.fields(data_cfg)},
    }

    # all_aligned SDF writer
    all_aligned_path = os.path.join(output_dir, "all_aligned.sdf")
    aligned_writer   = _AlignedSdfWriter(all_aligned_path)

    success_list: list = []
    skip_list:    list = []
    fail_list:    list = []
    t_batch_start = time.perf_counter()

    # 初始化 dashboard
    global _DASHBOARD
    _DASHBOARD = _Dashboard()
    _DASHBOARD.init(n_total, output_dir)

    # ── CPU worker pool 設定 ─────────────────────────────────────────────────
    use_mp    = (n_workers > 1 and n_total > 1)
    task_q    = multiprocessing.Queue(maxsize=n_workers * 3)
    result_q  = multiprocessing.Queue()

    if use_mp:
        workers = []
        for _ in range(n_workers):
            p = multiprocessing.Process(
                target=_worker_fn,
                args=(task_q, result_q, engine_kwargs, source),
                daemon=True)
            p.start()
            workers.append(p)

        # 生產者執行緒：把任務塞進 task_q
        def _producer():
            for idx, (mol_name_i, mol_raw_i, activity_i) in enumerate(records):
                if mol_name_i in completed_set:
                    result_q.put((idx, mol_name_i, "SKIP", None, 0.0, None))
                    continue
                is_smiles = (source == "smiles")
                block     = _mol_to_block(None, is_smiles, mol_raw_i)
                task_q.put((idx, mol_name_i, block, is_smiles, activity_i))
            # 送 sentinel
            for _ in range(n_workers):
                task_q.put(None)

        prod_thread = threading.Thread(target=_producer, daemon=True)
        prod_thread.start()

    else:
        # 單執行緒模式：直接在主迴圈呼叫 _prepare_mol
        pass

    # ── 主處理迴圈 ───────────────────────────────────────────────────────────
    pending = n_total   # 還未出結果的分子數

    def _process_one(idx, mol_name_i, mol_sdf_block, graph_dict, label, err):
        """處理單一分子的 GPU 計算 + 寫檔，更新統計。"""
        nonlocal pending

        if mol_sdf_block == "SKIP":
            skip_list.append(mol_name_i)
            return

        if err or mol_sdf_block is None:
            fail_list.append((mol_name_i, err or "worker 回傳空結果"))
            _DASHBOARD.log_error(mol_name_i, (err or "")[:80])
            return

        mol_out = _mol_from_sdf_block(mol_sdf_block)
        graph_i = _graph_from_dict(graph_dict, device)

        _DASHBOARD.update(
            len(success_list) + len(skip_list) + len(fail_list),
            len(success_list), len(skip_list), len(fail_list),
            time.perf_counter() - t_batch_start,
            mol_name_i, "GPU 計算中…")

        try:
            t_mol = time.perf_counter()
            results_i, pred_pic50_i = run_qsar_grid_map(
                model         = model,
                graph         = graph_i,
                device        = device,
                output_dir    = output_dir,
                mol_name      = mol_name_i,
                resolution    = resolution,
                padding       = padding,
                methods       = methods,
                sigma_scale   = sigma_scale,
                n_ig_steps    = n_ig_steps,
                perturb_batch = perturb_batch,
                aligned_mol   = mol_out,
                output_mode   = output_mode,
                silent        = True,
            )
            elapsed_mol = time.perf_counter() - t_mol

            aligned_writer.write(mol_out)
            completed_set.add(mol_name_i)
            _ckpt_save(output_dir, completed_set)
            success_list.append((mol_name_i, pred_pic50_i))

        except Exception as exc:
            reason = traceback.format_exc(limit=5)
            fail_list.append((mol_name_i, reason))
            _DASHBOARD.log_error(mol_name_i, str(exc)[:80])

    if use_mp:
        received = 0
        # 按照結果到達順序處理（不保序，但 checkpoint 是 set，無所謂）
        while received < n_total:
            idx_r, mol_name_r, sdf_r, gd_r, label_r, err_r = result_q.get()
            _process_one(idx_r, mol_name_r, sdf_r, gd_r, label_r, err_r)
            received += 1
            _DASHBOARD.update(
                received,
                len(success_list), len(skip_list), len(fail_list),
                time.perf_counter() - t_batch_start,
                mol_name_r, "完成" if err_r is None else "失敗")

        prod_thread.join()
        for p in workers:
            p.join(timeout=5)

    else:
        # 單執行緒：直接迭代
        for idx, (mol_name_i, mol_raw_i, activity_i) in enumerate(records):
            if mol_name_i in completed_set:
                skip_list.append(mol_name_i)
                _DASHBOARD.update(
                    idx + 1, len(success_list), len(skip_list), len(fail_list),
                    time.perf_counter() - t_batch_start, mol_name_i, "跳過(checkpoint)")
                continue

            mol_out, graph_i, label_i, err_i = _prepare_mol(
                mol_name_i, mol_raw_i, engine, activity=activity_i, source=source)

            if mol_out is None:
                fail_list.append((mol_name_i, err_i))
                _DASHBOARD.log_error(mol_name_i, (err_i or "")[:80])
            else:
                import io as _io
                from rdkit.Chem import SDWriter as _SDW
                sio = _io.StringIO()
                ww  = _SDW(sio); ww.write(mol_out); ww.flush()
                gd  = {
                    "x":          graph_i.x.numpy(),
                    "pos":        graph_i.pos.numpy(),
                    "edge_index": graph_i.edge_index.numpy(),
                    "edge_attr":  graph_i.edge_attr.numpy()
                                  if graph_i.edge_attr is not None else None,
                }
                _process_one(idx, mol_name_i, sio.getvalue(), gd, label_i, None)

            _DASHBOARD.update(
                idx + 1, len(success_list), len(skip_list), len(fail_list),
                time.perf_counter() - t_batch_start,
                mol_name_i, "完成")

    # ── 收尾 ────────────────────────────────────────────────────────────────
    aligned_writer.close()
    _DASHBOARD.finalize()

    total_elapsed = time.perf_counter() - t_batch_start

    _write_batch_summary(
        output_dir    = output_dir,
        records_total = n_total,
        success_list  = success_list,
        skip_list     = skip_list,
        fail_list     = fail_list,
        elapsed       = total_elapsed,
    )

    print("\n" + _hr("═"))
    print(_c("  批次完成", "bold", "green"))
    print(_hr())
    print(f"  成功   : {_c(str(len(success_list)), 'green')} 個分子")
    print(f"  略過   : {_c(str(len(skip_list)),    'cyan')}  個（checkpoint 已完成）")
    print(f"  失敗   : {_c(str(len(fail_list)),    'red')}  個分子")
    print(f"  耗時   : {total_elapsed:.1f} 秒 ({total_elapsed/60:.1f} 分鐘)")
    print(f"  對齊SDF: {_c('all_aligned.sdf', 'yellow')}  ({aligned_writer.count} 個分子)")
    print(f"  輸出格式: {_c(output_mode, 'cyan')}")
    print(f"  輸出目錄: {_c(os.path.abspath(output_dir), 'cyan')}")
    if output_mode == "npz":
        print(_c("  ℹ  用 npz_to_cube('路徑/分子名.npz') 將指定分子轉換為 .cube", "dim"))
    if fail_list:
        print(_c(f"  ⚠  {len(fail_list)} 個分子失敗，詳見 batch_summary.txt", "yellow"))
    if len(fail_list) < n_total:
        print(_c("  ℹ  若需重試失敗分子，直接重執行，checkpoint 自動略過已完成項目。", "dim"))
    print(_hr("═") + "\n")


if __name__ == "__main__":
    main()
